export type UiLanguage = "cs" | "en";
export const uiLanguageCookieName = "harness_ui_lang";

export function resolveUiLanguage(value: string | undefined): UiLanguage {
  return value === "en" ? "en" : "cs";
}

export function withLang(path: string, lang: UiLanguage) {
  return lang === "cs" ? path : `${path}${path.includes("?") ? "&" : "?"}lang=${lang}`;
}

export const publicCopy = {
  cs: {
    brand: "harness lab",
    navOverview: "přehled",
    navPrinciples: "principy",
    navDetails: "detaily",
    navBlueprint: "blueprint",
    navParticipantAccess: "vstup pro účastníky",
    navRepo: "repo",
    navRoom: "místnost",
    navTeams: "týmy",
    navNotes: "poznámky",
    navFacilitatorLogin: "vstup pro facilitátora",
    heroEyebrow: "workshop pro týmy, které pracují s ai coding agenty",
    heroLead: "Celodenní workshop o tom, jak v týmu pracovat s AI coding agenty na skutečném softwaru.",
    heroBody:
      "Nejde o demo promptů ani o jednorázové hacky. Jde o kontext, rozhodnutí, ověřování a způsob práce, na který může navázat další člověk i další agent.",
    blueprintLink: "otevřít workshop blueprint",
    blueprintHint:
      "Veřejný blueprint workshopu: jak je postavený den, co patří do repa a co až do živé workshop instance.",
    accessEyebrow: "vstup pro účastníky",
    accessTitle: "vstup do kontextu místnosti",
    accessBody:
      "Pokud jste fyzicky v místnosti, facilitátor sdílí event code. Bez něj tato stránka zůstává veřejným přehledem Harness Labu.",
    eventCodeLabel: "event code",
    eventCodePlaceholder: "sdílí facilitátor",
    eventCodeSubmit: "otevřít vrstvu pro účastníky",
    facilitatorLogin: "vstup pro facilitátora",
    publicDetails: "veřejné detaily",
    sampleHint: "Lokální demo běží se sample kódem, proto je pole předvyplněné. V preview a produkci to tak být nemá.",
    principlesEyebrow: "principy",
    principlesTitle: "tři pravidla, díky kterým je práce s agenty čitelná, ověřitelná a udržitelná.",
    principleOneTitle: "mapa před pohybem",
    principleOneBody:
      "Než pustíte další generování, udělejte z repa místo, kde se dá orientovat. Krátké `AGENTS.md`, jasný vstupní bod a viditelný další safe move jsou lepší než další prompt navíc.",
    principleTwoTitle: "ověřujte dřív, než jdete dál",
    principleTwoBody:
      "Každý důležitý posun co nejdřív opřete o důkaz. Menší ověřený krok je cennější než rychlý postup, který se později rozpadne.",
    principleThreeTitle: "pracujte tak, aby se dalo navázat",
    principleThreeBody:
      "Další člověk ani další agent nemá hádat, co se stalo. V repu má být jasné, co platí, co je skutečně ověřené a jaký je bezpečný další krok.",
    detailsWhat: "co to je",
    detailsWhatBody:
      "Harness Lab je praktický workshop o tom, jak používat AI coding agenty při skutečné týmové práci na softwaru. Důraz je na způsob práce, který zůstává srozumitelný, ověřitelný a použitelný i po dalším předání.",
    detailsParticipants: "pro účastníky",
    detailsParticipantsBody:
      "Účastníci dostanou kontext své místnosti až po zadání event code. Veřejná stránka zůstává záměrně obecná a neukazuje živý stav konkrétní workshop instance.",
    detailsBoundary: "co zůstává neveřejné",
    detailsBoundaryBody:
      "Konkrétní termín, místnost, složení týmů i facilitace patří do privátní workshop instance. Veřejný dashboard a public repo zůstávají bezpečné a přenositelné.",
    detailsBlueprint: "blueprint workshopu",
    detailsBlueprintBody:
      "Workshopová metoda má v repu vlastní blueprint. Dashboard řídí běžící workshop, ale kanonický popis dne, pravidel a hranic editace zůstává tady.",
    footerBody: "Veřejný přehled workshopu o týmové práci s AI coding agenty.",
    footerTop: "nahoru",
    footerParticipantAccess: "vstup pro účastníky",
    footerBlueprint: "blueprint",
    participantEyebrow: "vrstva pro účastníky",
    participantTitleFallback: "workshop běží",
    participantBodyRevealed:
      "Continuation shift je odemčený. Nejdřív čtěte README, `AGENTS.md` a plán. Sepište si, co pomáhá, co chybí a jaký je další safe move, pak teprve měňte kód.",
    participantBodyHidden:
      "Soustřeďte se na krátké `AGENTS.md`, plán, build/test flow a první ověřený krok. Continuation shift se odemkne později.",
    participantGuidanceFallbackLabel: "agenda pro tým",
    participantGuidanceFocusTitle: "co držet teď",
    participantGuidancePreviewBody:
      "Držte pohromadě live moment, další blok a sdílené poznámky z místnosti. Když se zaseknete, vraťte se k mapě repa a nejmenšímu užitečnému ověření.",
    metricCurrentPhase: "aktuální fáze",
    metricNext: "další blok",
    metricSessionUntil: "session do",
    metricReflection: "reflexe",
    sessionEyebrow: "session",
    sessionBody: "Přihlášení platí jen pro data této místnosti. Facilitátor zůstává odděleně na `/admin`.",
    leaveRoomContext: "opustit kontext místnosti",
    roomData: "vaše data z místnosti",
    noRoomData: "Pro tuto session zatím nejsou dostupná žádná data z konkrétní místnosti.",
    sharedRoomNotes: "sdílené poznámky z místnosti",
    invalidCode: "Event code nesedí. Použijte kód sdílený facilitátorem pro tuto místnost.",
    expiredCode: "Tento event code už expiroval. Facilitátor musí vydat nový nebo ho obnovit.",
    unknownCodeError: "Privátní kontext místnosti se nepodařilo odemknout.",
  },
  en: {
    brand: "harness lab",
    navOverview: "overview",
    navPrinciples: "principles",
    navDetails: "details",
    navBlueprint: "blueprint",
    navParticipantAccess: "participant access",
    navRepo: "repo",
    navRoom: "room",
    navTeams: "teams",
    navNotes: "notes",
    navFacilitatorLogin: "facilitator login",
    heroEyebrow: "workshop for teams working with ai coding agents",
    heroLead: "A full-day workshop on how teams work with AI coding agents on real software.",
    heroBody:
      "This is not prompt theatre or one-off hacking. It is about context, decisions, verification, and a way of working that another person or another agent can continue.",
    blueprintLink: "open workshop blueprint",
    blueprintHint:
      "The public workshop blueprint: how the day is structured, what belongs in the repo, and what only exists in the live workshop instance.",
    accessEyebrow: "participant access",
    accessTitle: "enter room context",
    accessBody:
      "If you are physically in the room, the facilitator shares the event code. Without it, this page stays a public overview of Harness Lab.",
    eventCodeLabel: "event code",
    eventCodePlaceholder: "shared by facilitator",
    eventCodeSubmit: "open participant view",
    facilitatorLogin: "facilitator login",
    publicDetails: "public details",
    sampleHint: "Local demo mode uses a sample code, so the field is prefilled. This should not happen in preview or production.",
    principlesEyebrow: "principles",
    principlesTitle: "three rules that keep work with agents legible, verifiable, and maintainable.",
    principleOneTitle: "map before motion",
    principleOneBody:
      "Before you ask for more generation, make the repo navigable. A short `AGENTS.md`, a clear entry point, and an obvious next safe step beat one more prompt blob.",
    principleTwoTitle: "verify before you move on",
    principleTwoBody:
      "Anchor each meaningful step in evidence as early as possible. A smaller verified step is worth more than a faster path that falls apart later.",
    principleThreeTitle: "work so others can continue",
    principleThreeBody:
      "The next person or the next agent should not have to guess what happened. The repo should make clear what holds, what is actually verified, and what the next safe step is.",
    detailsWhat: "what it is",
    detailsWhatBody:
      "Harness Lab is a practical workshop about using AI coding agents in real team software work. The focus is on a way of working that stays understandable, verifiable, and usable through handoffs.",
    detailsParticipants: "for participants",
    detailsParticipantsBody:
      "Participants get room-specific context only after the event code. The public page stays intentionally general and does not expose the live state of a specific workshop instance.",
    detailsBoundary: "what stays private",
    detailsBoundaryBody:
      "Real dates, rooms, team assignments, and facilitation data belong in the private workshop instance. The public repo and homepage stay safe and portable.",
    detailsBlueprint: "workshop blueprint",
    detailsBlueprintBody:
      "The workshop method has its own blueprint in the repo. The dashboard operates the live workshop, while the canonical day design, rules, and edit boundaries stay there.",
    footerBody: "Public overview of a workshop about team work with AI coding agents.",
    footerTop: "top",
    footerParticipantAccess: "participant access",
    footerBlueprint: "blueprint",
    participantEyebrow: "participant room",
    participantTitleFallback: "workshop running",
    participantBodyRevealed:
      "The continuation shift is unlocked. Read README, `AGENTS.md`, and the plan first. Write down what helps, what is missing, and the next safe move before you change code.",
    participantBodyHidden:
      "Focus on a short `AGENTS.md`, the plan, the build/test flow, and the first verified step. The continuation shift will unlock later.",
    participantGuidanceFallbackLabel: "team agenda",
    participantGuidanceFocusTitle: "what to hold now",
    participantGuidancePreviewBody:
      "Keep the live moment, the next block, and shared room notes in view together. If you get stuck, go back to the repo map and the smallest useful verification step.",
    metricCurrentPhase: "current phase",
    metricNext: "next",
    metricSessionUntil: "session until",
    metricReflection: "reflection",
    sessionEyebrow: "session",
    sessionBody: "This sign-in only applies to data for this room. Facilitator access stays separate at `/admin`.",
    leaveRoomContext: "leave room context",
    roomData: "your room data",
    noRoomData: "No room-specific data is available for this session yet.",
    sharedRoomNotes: "shared room notes",
    invalidCode: "The event code does not match. Use the code shared by the facilitator for this room.",
    expiredCode: "This event code has expired. The facilitator must issue a new one or restore it.",
    unknownCodeError: "The private room context could not be unlocked.",
  },
} satisfies Record<UiLanguage, Record<string, string>>;

export const adminCopy = {
  cs: {
    deskEyebrow: "facilitator desk",
    pageTitle: "řízení workspace",
    pageBody: "Výběr instancí, vstup do control room a klíčové facilitátorské operace na jednom místě.",
    workspaceEyebrow: "workspace cockpit",
    workspaceTitle: "workshopy a jejich instance",
    workspaceBody: "Přehled všech workshopů: co existuje, co je připravené a odkud vstoupit do konkrétního live řízení.",
    workspaceSummaryTitle: "workspace na první pohled",
    workspaceSearchLabel: "hledat workshop",
    workspaceSearchPlaceholder: "název, id, venue nebo facilitátor",
    workspaceStatusFilterLabel: "stav",
    workspaceSearchButton: "použít filtry",
    workspaceResetFilters: "vyčistit",
    workspaceEmptyTitle: "žádná instance neodpovídá filtru",
    workspaceEmptyBody: "Zkuste jiný dotaz nebo stav. Workspace má ukazovat všechny akce čitelně, ne vás nutit hádat správné id.",
    workspaceOpenInstance: "otevřít řízení",
    workspaceCreateDescription: "Nejdřív event record. Pak control room. Zadejte název akce, datum a místo.",
    workspaceCreateStepsTitle: "co se stane dál",
    workspaceCreateStepOne: "instance se objeví ve workspace přehledu",
    workspaceCreateStepTwo: "otevře se její control room pro live řízení",
    workspaceCreateStepThree: "participant vrstva zůstává oddělená a scoped na tuto akci",
    workspaceStatsAll: "celkem",
    workspaceStatsCreated: "nové",
    workspaceStatsPrepared: "připravené",
    workspaceStatsRunning: "live",
    workspaceStatsArchived: "archiv",
    workspaceWhenLabel: "termín",
    workspaceWhereLabel: "kde",
    workspaceOwnerLabel: "vlastník",
    workspacePhaseLabel: "fáze",
    workspaceTeamsLabel: "týmy",
    workspaceNextStepLabel: "další krok",
    workspaceNextStepCreated: "Doplňte runtime data a otevřete control room.",
    workspaceNextStepPrepared: "Zkontrolujte live fázi, týmy, participant access a jestli checkpointy chtějí evidence místo dojmů.",
    workspaceNextStepRunning: "Použijte control room pro live zásahy a signály.",
    workspaceNextStepArchived: "Zachovejte historii a případně připravte další běh.",
    workspaceSignalLabel: "participant vrstva",
    workspaceSignalHidden: "stále skrytá",
    workspaceSignalRevealed: "continuation odemčeno",
    controlRoomBack: "zpět na workspace",
    controlRoomBody: "Řízení jedné konkrétní akce. Stav, navigace i zásahy jsou scoped jen na tuto instanci.",
    navOverview: "přehled",
    navLive: "live",
    navAgenda: "agenda",
    navTeams: "týmy",
    navSignals: "signály",
    navAccess: "přístupy",
    navSettings: "nastavení",
    navAccount: "účet",
    activeInstance: "aktivní instance",
    instanceIdLabel: "id instance",
    instanceStatusCreated: "nové",
    instanceStatusPrepared: "připravené",
    instanceStatusRunning: "live",
    instanceStatusArchived: "archivováno",
    instanceStatusRemoved: "odebráno",
    currentPhase: "aktuální fáze",
    rotation: "rotace",
    teams: "týmy",
    liveNow: "právě běží",
    nextUp: "dále",
    signedInAs: "přihlášen jako",
    rotationUnlocked: "odemčeno",
    rotationHidden: "skryto",
    latestArchivePrefix: "Poslední archiv:",
    retentionUntil: "retention do",
    retentionUnset: "nenastaveno",
    sectionHint: "Navigace zůstává lehká. Stav je stále vidět nahoře, samotné zásahy žijí v oddělených blocích.",
    instanceSwitcherTitle: "scope ovládání",
    instanceSwitcherDescription: "Vyberte instanci, se kterou právě pracujete. Všechny zásahy níže míří jen do ní.",
    instanceSelectLabel: "varianta workshopu",
    instanceSelectHint: "Tahle volba zatím mění hlavně participant scénář a rotační setup podle velikosti skupiny.",
    instanceBlueprintSummary: "Použije se jediný výchozí blueprint pro střední skupinu, zhruba 15 až 20 lidí.",
    switchInstanceButton: "přepnout instanci",
    createInstanceTitle: "vytvořit novou instanci",
    createInstanceEventTitleLabel: "název akce",
    createInstanceEventTitlePlaceholder: "Harness Lab pro Acme",
    newInstanceIdPlaceholder: "client-hackathon-2026-05",
    instanceDateLabel: "datum",
    instanceVenueLabel: "venue / budova",
    instanceAreaLabel: "lokalita / zóna",
    instanceAddressLabel: "adresa",
    instanceCityPlaceholder: "Studio A",
    instanceDateRangePlaceholder: "12. května 2026",
    instanceVenuePlaceholder: "Venue / budova",
    instanceRoomLabel: "místnost",
    instanceRoomPlaceholder: "Room / patro",
    instanceAddressPlaceholder: "Adresa nebo orientační bod",
    instanceLocationDetailsPlaceholder: "Další detaily pro facilitátora",
    instanceOwnerPlaceholder: "Ondrej / facilitator crew",
    createInstanceButton: "vytvořit instanci",
    removeInstanceTitle: "odebrat aktivní instanci",
    removeInstanceHint: "Odebere ji z aktivního seznamu, ale ponechá archivní historii.",
    removeInstanceButton: "odebrat instanci",
    overviewTitle: "live řízení",
    overviewDescription: "Jeden přehled toho, co právě běží, co následuje a co dává smysl udělat teď.",
    workshopStateTitle: "stav workshopu",
    workshopStateEyebrow: "rychlé zásahy do průběhu dne",
    workshopStateDescription: "Použijte na změnu fáze a reset instance. Reset je high-impact operace.",
    moveAgendaTitle: "řízení fáze",
    setCurrentPhase: "posunout live marker",
    agendaSectionTitle: "agenda a fáze",
    agendaSectionDescription: "Tady je vidět celý průběh dne, aktuální položka a vysvětlení, odkud se agenda bere.",
    agendaTimelineTitle: "timeline dne",
    agendaCurrentTitle: "live fáze",
    phaseControlHint: "Needitujete blueprint. Jen přesouváte live marker v runtime instanci.",
    agendaStatusDone: "hotovo",
    agendaStatusCurrent: "právě teď",
    agendaStatusUpcoming: "následuje",
    agendaEditEyebrow: "lokální editace této instance",
    agendaEditTitle: "upravit vybranou položku",
    agendaEditDescription: "Tady upravujete runtime kopii agendy pro tuto instanci. Reset tyto změny zahodí a znovu naimportuje blueprint.",
    saveAgendaItemButton: "uložit položku",
    addAgendaItemTitle: "přidat lokální položku",
    addAgendaItemDescription: "Přidejte položku, která platí jen pro tuto workshop instanci.",
    addAgendaItemButton: "přidat položku",
    moveUpButton: "posunout výš",
    moveDownButton: "posunout níž",
    removeAgendaItemButton: "odebrat položku",
    agendaSourceTitle: "kde se agenda upravuje",
    agendaSourceBody:
      "Tato stránka pracuje s runtime kopií agendy pro vybranou instanci. Blueprint zůstává kanonický pro nové importy a reset, ale lokální pořadí, názvy, časy i doplněné položky můžete upravit tady bez zásahu do sdíleného blueprintu.",
    resetInstanceTitle: "reset workshop instance",
    resetHint: "Znovu naimportuje workshop blueprint do této instance a vyčistí lokální runtime stav.",
    resetBlueprintSummary: "Reset vrátí instanci na jediný výchozí blueprint pro střední skupinu.",
    resetButton: "resetovat data",
    archiveTitle: "archivovat aktuální instanci",
    archivePlaceholder: "volitelné poznámky k archivaci",
    archiveHint: "Uloží snapshot runtime stavu před closeoutem nebo před ručním resetem.",
    archiveButton: "vytvořit archiv",
    continuationTitle: "continuation handoff",
    continuationEyebrow: "odemknutí handoff momentu",
    continuationDescription: "Přepínač pro moment, kdy se má účastníkům otevřít continuation část dne.",
    revealTitle: "stav continuation",
    unlockButton: "odemknout",
    hideAgainButton: "znovu skrýt",
    participantStatePrefix: "Stav na participant ploše:",
    participantStateUnlocked: "předání je odemčeno",
    participantStateHidden: "předání je skryté",
    presenterCardTitle: "projekce pro místnost",
    presenterCardDescription: "Spusťte výstup pro projekci v místnosti. Výchozí scéna se řídí aktivní položkou agendy a můžete ji kdykoli přepnout.",
    presenterCurrentSceneLabel: "výchozí scéna",
    presenterOpenCurrentButton: "otevřít projekci",
    presenterOpenParticipantButton: "průchod participant vrstvou",
    presenterOpenSelectedScene: "otevřít tuto scénu",
    presenterSceneDisabled: "skryto",
    presenterPageEyebrow: "projekce pro místnost",
    presenterBack: "zpět do režie",
    presenterAgendaLabel: "agenda",
    presenterScenesLabel: "scény",
    presenterNoSceneTitle: "Pro tuto položku zatím není připravená žádná aktivní scéna.",
    presenterNoSceneBody: "Použijte skill nebo facilitator API a doplňte obsah pro projekci pro tuto část agendy.",
    presenterParticipantPreviewLabel: "náhled participant vrstvy",
    presenterCueLabel: "co má místnost vidět teď",
    presenterRoomPulseLabel: "signál z místnosti",
    activeRotationTitle: "aktivní rozpis rotace",
    archiveResetTitle: "bezpečnostní zásahy",
    archiveResetDescription: "Archiv a reset patří do druhé vrstvy. Používejte je vědomě, ne místo primárních zásahů.",
    blueprintLinkLabel: "upravit blueprint",
    blueprintLinkHint: "Blueprint upravujte jen tehdy, když chcete změnit výchozí podobu workshopu pro budoucí importy. Jednorázové úpravy této akce patří do runtime instance.",
    teamOpsTitle: "operace nad týmy",
    teamOpsEyebrow: "repo a checkpoint management",
    teamOpsDescription: "Vyberte tým a upravujte ho v kontextu repo URL, členů a checkpointu. Nový tým založte zvlášť.",
    registerTeamTitle: "registrovat nebo upravit tým",
    editTeamTitle: "upravit vybraný tým",
    editTeamDescription: "Editace je navázaná na zvolený tým, takže nemusíte ručně párovat id a jméno.",
    checkpointFormHint: "Checkpointy zapisujte jako evidence: co se změnilo, co to ověřuje a jaký je další safe move.",
    checkpointChangedLabel: "co se změnilo",
    checkpointVerifiedLabel: "co to ověřuje",
    checkpointNextStepLabel: "další safe move",
    checkpointAtLabel: "čas",
    teamNamePlaceholder: "Tým 5",
    teamCheckpointPlaceholder: "co se změnilo / co to ověřuje / další safe move",
    createTeamButton: "vytvořit tým",
    updateTeamButton: "uložit změny týmu",
    createAnotherTeamLabel: "nový tým",
    editActionLabel: "upravit",
    saveTeamButton: "uložit tým",
    editCheckpointTitle: "upravit checkpoint týmu",
    saveCheckpointButton: "uložit checkpoint",
    signalTitle: "sběr signálů",
    signalEyebrow: "intermezzo a progress evidence",
    signalDescription: "Krátké zápisy do feedu a challenge completion. Preferujte evidence typu co se změnilo, co to ověřuje a co má další tým číst jako první.",
    sprintFeedTitle: "feed sprint checkpointů",
    addUpdateButton: "přidat update",
    completeChallengeTitle: "označit challenge jako splněnou",
    recordCompletionButton: "zapsat completion",
    signInTitle: "přihlášení facilitátora",
    signInBody: "Přístup k operačnímu panelu vyžaduje přihlášení.",
    signInEmailLabel: "e-mail",
    signInPasswordLabel: "heslo",
    signInButton: "přihlásit se",
    signInError: "Neplatné přihlašovací údaje.",
    signOutButton: "odhlásit se",
    signInBackLink: "← zpět na přehled",
    facilitatorsTitle: "správa facilitátorů",
    facilitatorsEyebrow: "přístupy k instanci",
    facilitatorsDescription: "Přidání a odebrání facilitátorů pro tuto workshop instanci.",
    addFacilitatorTitle: "přidat facilitátora",
    facilitatorEmailPlaceholder: "email@example.com",
    facilitatorRoleLabel: "role",
    addFacilitatorButton: "přidat",
    revokeButton: "odebrat",
    facilitatorListEmpty: "Žádné aktivní přístupy.",
    fileModeFacilitators: "Správa facilitátorů vyžaduje neon mód.",
    fileModeFacilitatorsPanelTitle: "lokální přístup v file módu",
    fileModeFacilitatorsPanelBody:
      "Tato instance běží bez per-user grantů. Přístup je sdílený přes lokální Basic Auth a scope zůstává na úrovni celé instance.",
    fileModeAuthModeLabel: "režim přístupu",
    fileModeAuthModeValue: "Basic Auth / sdílený lokální přístup",
    fileModeUsernameLabel: "uživatelské jméno",
    fileModeScopeLabel: "scope",
    fileModeScopeValue: "jedna lokální identita pro celý facilitator desk",
    fileModeUpgradeTitle: "co přidá neon mód",
    fileModeUpgradeBody: "Jakmile poběžíte v neon módu, tahle sekce se změní z fallbacku na reálnou správu přístupů.",
    fileModeUpgradeBenefitOne: "samostatné účty facilitátorů a role owner / operator / observer",
    fileModeUpgradeBenefitTwo: "odebírání přístupu bez sdíleného hesla",
    fileModeUpgradeBenefitThree: "navázání session a audit logu na konkrétní osobu",
    accountTitle: "účet facilitátora",
    accountEyebrow: "heslo a session",
    accountDescription: "Správa vlastního přihlášení a rychlý přehled role v aktuální instanci.",
    passwordCardTitle: "změnit heslo",
    currentPasswordLabel: "aktuální heslo",
    newPasswordLabel: "nové heslo",
    confirmPasswordLabel: "potvrzení nového hesla",
    revokeSessionsLabel: "odhlásit ostatní session",
    changePasswordButton: "uložit nové heslo",
    passwordChanged: "Heslo bylo změněno.",
    passwordMismatch: "Nová hesla se neshodují.",
    passwordResetTitle: "pomoc s heslem",
    passwordResetBody: "Pokud si heslo nepamatujete, pošlete si resetovací odkaz na e-mail.",
    passwordResetButton: "poslat reset odkaz",
    passwordResetSent: "Pokud účet existuje a reset je dostupný, e-mail byl odeslán.",
    passwordResetPageTitle: "nastavit nové heslo",
    passwordResetPageBody: "Použijte odkaz z e-mailu a nastavte nové heslo pro facilitátorský účet.",
    passwordResetMissingToken: "Reset link neobsahuje token. Otevřete stránku z e-mailu znovu.",
    passwordResetButtonConfirm: "nastavit nové heslo",
    passwordResetDone: "Heslo bylo resetováno. Přihlaste se novým heslem.",
    accountFileMode: "Správa hesla je dostupná jen v neon módu.",
    resetHelpTitle: "potřebujete změnit heslo?",
    resetHelpBody:
      "Přihlášení řeší Neon Auth. Pokud heslo znáte, po přihlášení ho změníte v sekci Účet. Pokud ho neznáte, můžete si poslat resetovací odkaz rovnou odsud.",
  },
  en: {
    deskEyebrow: "facilitator desk",
    pageTitle: "workspace operations",
    pageBody: "Instance selection, control-room entry, and key facilitator operations in one place.",
    workspaceEyebrow: "workspace cockpit",
    workspaceTitle: "workshops and instances",
    workspaceBody: "A clear view of all workshop events: what exists, what is ready, and where to enter focused live control.",
    workspaceSummaryTitle: "workspace at a glance",
    workspaceSearchLabel: "search workshops",
    workspaceSearchPlaceholder: "title, id, venue, or facilitator",
    workspaceStatusFilterLabel: "status",
    workspaceSearchButton: "apply filters",
    workspaceResetFilters: "clear",
    workspaceEmptyTitle: "no instances match the current filters",
    workspaceEmptyBody: "Try a different query or status. The workspace should make events legible, not force you to guess ids.",
    workspaceOpenInstance: "open control room",
    workspaceCreateDescription: "Start with the event record, then enter the control room. Set the event title, date, and place.",
    workspaceCreateStepsTitle: "what happens next",
    workspaceCreateStepOne: "the instance appears in the workspace overview",
    workspaceCreateStepTwo: "its control room opens for live operation",
    workspaceCreateStepThree: "the participant surface stays separate and scoped to this event",
    workspaceStatsAll: "all",
    workspaceStatsCreated: "draft",
    workspaceStatsPrepared: "ready",
    workspaceStatsRunning: "live",
    workspaceStatsArchived: "archive",
    workspaceWhenLabel: "schedule",
    workspaceWhereLabel: "where",
    workspaceOwnerLabel: "owner",
    workspacePhaseLabel: "phase",
    workspaceTeamsLabel: "teams",
    workspaceNextStepLabel: "next step",
    workspaceNextStepCreated: "Add runtime details and enter the control room.",
    workspaceNextStepPrepared: "Check the live phase, teams, participant access, and whether checkpoints ask for evidence instead of vibes.",
    workspaceNextStepRunning: "Use the control room for live interventions and signals.",
    workspaceNextStepArchived: "Keep the history intact and prepare the next run if needed.",
    workspaceSignalLabel: "participant surface",
    workspaceSignalHidden: "still hidden",
    workspaceSignalRevealed: "continuation unlocked",
    controlRoomBack: "back to workspace",
    controlRoomBody: "Operate one specific event. Status, navigation, and actions are scoped to this instance only.",
    navOverview: "overview",
    navLive: "live",
    navAgenda: "agenda",
    navTeams: "teams",
    navSignals: "signals",
    navAccess: "access",
    navSettings: "settings",
    navAccount: "account",
    activeInstance: "active instance",
    instanceIdLabel: "instance id",
    instanceStatusCreated: "draft",
    instanceStatusPrepared: "ready",
    instanceStatusRunning: "live",
    instanceStatusArchived: "archived",
    instanceStatusRemoved: "removed",
    currentPhase: "current phase",
    rotation: "rotation",
    teams: "teams",
    liveNow: "live now",
    nextUp: "next up",
    signedInAs: "signed in as",
    rotationUnlocked: "unlocked",
    rotationHidden: "hidden",
    latestArchivePrefix: "Latest archive:",
    retentionUntil: "retention until",
    retentionUnset: "not set",
    sectionHint: "Navigation stays light. Status stays visible at the top, and actions live in their own sections.",
    instanceSwitcherTitle: "control scope",
    instanceSwitcherDescription: "Choose the instance you are operating. Every action below applies only to that instance.",
    instanceSelectLabel: "workshop variant",
    instanceSelectHint: "This currently changes the participant scenario and rotation setup based on group size.",
    instanceBlueprintSummary: "This uses the single default blueprint for a medium-sized group, about 15 to 20 people.",
    switchInstanceButton: "switch instance",
    createInstanceTitle: "create a new instance",
    createInstanceEventTitleLabel: "event title",
    createInstanceEventTitlePlaceholder: "Harness Lab for Acme",
    newInstanceIdPlaceholder: "client-hackathon-2026-05",
    instanceDateLabel: "date",
    instanceVenueLabel: "venue / building",
    instanceAreaLabel: "area / zone",
    instanceAddressLabel: "address",
    instanceCityPlaceholder: "Studio A",
    instanceDateRangePlaceholder: "May 12, 2026",
    instanceVenuePlaceholder: "venue / building",
    instanceRoomLabel: "room",
    instanceRoomPlaceholder: "room / floor",
    instanceAddressPlaceholder: "address or landmark",
    instanceLocationDetailsPlaceholder: "additional facilitator-only context",
    instanceOwnerPlaceholder: "Ondrej / facilitator crew",
    createInstanceButton: "create instance",
    removeInstanceTitle: "remove active instance",
    removeInstanceHint: "Removes it from the active list while keeping archive history intact.",
    removeInstanceButton: "remove instance",
    overviewTitle: "live control",
    overviewDescription: "One view of what is live, what comes next, and which facilitator actions matter right now.",
    workshopStateTitle: "workshop state",
    workshopStateEyebrow: "quick interventions during the day",
    workshopStateDescription: "Use this area to change the phase or reset the instance. Reset is a high-impact operation.",
    moveAgendaTitle: "phase control",
    setCurrentPhase: "move live marker",
    agendaSectionTitle: "agenda and phase",
    agendaSectionDescription: "This view shows the full workshop timeline, the current item, and where the agenda actually comes from.",
    agendaTimelineTitle: "day timeline",
    agendaCurrentTitle: "live phase",
    phaseControlHint: "This does not edit the blueprint. It only moves the live agenda marker inside the runtime instance.",
    agendaStatusDone: "done",
    agendaStatusCurrent: "live now",
    agendaStatusUpcoming: "up next",
    agendaEditEyebrow: "local editing for this instance",
    agendaEditTitle: "edit selected item",
    agendaEditDescription: "This edits the runtime copy of the agenda for this instance. Reset discards these changes and re-imports from the blueprint.",
    saveAgendaItemButton: "save item",
    addAgendaItemTitle: "add local item",
    addAgendaItemDescription: "Add an agenda item that exists only for this workshop instance.",
    addAgendaItemButton: "add item",
    moveUpButton: "move up",
    moveDownButton: "move down",
    removeAgendaItemButton: "remove item",
    agendaSourceTitle: "where the agenda is edited",
    agendaSourceBody:
      "This page works on the runtime agenda copy for the selected instance. The blueprint remains canonical for future imports and resets, but local order, labels, times, and added items can be changed here without mutating the shared blueprint.",
    resetInstanceTitle: "reset workshop instance",
    resetHint: "This re-imports the workshop blueprint into this instance and clears local runtime state.",
    resetBlueprintSummary: "Reset restores the single default blueprint for a medium-sized group.",
    resetButton: "reset data",
    archiveTitle: "archive current instance",
    archivePlaceholder: "optional archive notes",
    archiveHint: "Stores a runtime snapshot before closeout or before a manual reset.",
    archiveButton: "create archive",
    continuationTitle: "continuation handoff",
    continuationEyebrow: "unlock the handoff moment",
    continuationDescription: "The switch for the moment when participants should see the continuation part of the day.",
    revealTitle: "continuation state",
    unlockButton: "unlock",
    hideAgainButton: "hide again",
    participantStatePrefix: "Participant surface state:",
    participantStateUnlocked: "handoff is unlocked",
    participantStateHidden: "handoff is hidden",
    presenterCardTitle: "room screen",
    presenterCardDescription: "Launch the presenter-safe room output. The default scene follows the active agenda item and can be switched at any time.",
    presenterCurrentSceneLabel: "default scene",
    presenterOpenCurrentButton: "open room screen",
    presenterOpenParticipantButton: "participant walkthrough",
    presenterOpenSelectedScene: "open this scene",
    presenterSceneDisabled: "hidden",
    presenterPageEyebrow: "room screen",
    presenterBack: "back to control room",
    presenterAgendaLabel: "agenda",
    presenterScenesLabel: "scenes",
    presenterNoSceneTitle: "There is no active scene configured for this agenda item yet.",
    presenterNoSceneBody: "Use the skill or facilitator API to add room-facing content for this part of the agenda.",
    presenterParticipantPreviewLabel: "participant preview",
    presenterCueLabel: "what the room should see now",
    presenterRoomPulseLabel: "room pulse",
    activeRotationTitle: "active rotation plan",
    archiveResetTitle: "safety actions",
    archiveResetDescription: "Archive and reset belong on a second layer. They should never compete with the primary controls.",
    blueprintLinkLabel: "edit blueprint",
    blueprintLinkHint: "Edit the blueprint only when you want to change the workshop default for future imports. One-off event changes belong in the runtime instance.",
    teamOpsTitle: "team operations",
    teamOpsEyebrow: "repo and checkpoint management",
    teamOpsDescription: "Operate around real teams. Select a team to edit repo URL, members, and checkpoint in context, and create new teams separately.",
    registerTeamTitle: "register or edit team",
    editTeamTitle: "edit selected team",
    editTeamDescription: "Editing stays attached to the selected team so you do not have to manually match ids and names.",
    checkpointFormHint: "Capture checkpoints as evidence: what changed, what verifies it, and the next safe move.",
    checkpointChangedLabel: "what changed",
    checkpointVerifiedLabel: "what verifies it",
    checkpointNextStepLabel: "next safe move",
    checkpointAtLabel: "time",
    teamNamePlaceholder: "Team 5",
    teamCheckpointPlaceholder: "what changed / what verifies it / next safe move",
    createTeamButton: "create team",
    updateTeamButton: "save team changes",
    createAnotherTeamLabel: "new team",
    editActionLabel: "edit",
    saveTeamButton: "save team",
    editCheckpointTitle: "edit team checkpoint",
    saveCheckpointButton: "save checkpoint",
    signalTitle: "signal capture",
    signalEyebrow: "intermezzo and progress evidence",
    signalDescription: "Short feed updates and challenge completion. Prefer evidence such as what changed, what verifies it, and what the next team should read first.",
    sprintFeedTitle: "sprint checkpoint feed",
    addUpdateButton: "add update",
    completeChallengeTitle: "mark challenge as completed",
    recordCompletionButton: "record completion",
    signInTitle: "facilitator sign-in",
    signInBody: "Access to the operations panel requires authentication.",
    signInEmailLabel: "email",
    signInPasswordLabel: "password",
    signInButton: "sign in",
    signInError: "Invalid credentials.",
    signOutButton: "sign out",
    signInBackLink: "← back to overview",
    facilitatorsTitle: "facilitator management",
    facilitatorsEyebrow: "instance access",
    facilitatorsDescription: "Add and remove facilitators for this workshop instance.",
    addFacilitatorTitle: "add facilitator",
    facilitatorEmailPlaceholder: "email@example.com",
    facilitatorRoleLabel: "role",
    addFacilitatorButton: "add",
    revokeButton: "revoke",
    facilitatorListEmpty: "No active grants.",
    fileModeFacilitators: "Facilitator management requires neon mode.",
    fileModeFacilitatorsPanelTitle: "local access in file mode",
    fileModeFacilitatorsPanelBody:
      "This instance is running without per-user grants. Access is shared through local Basic Auth and the scope stays at the whole-instance level.",
    fileModeAuthModeLabel: "access mode",
    fileModeAuthModeValue: "Basic Auth / shared local access",
    fileModeUsernameLabel: "username",
    fileModeScopeLabel: "scope",
    fileModeScopeValue: "one local identity for the whole facilitator desk",
    fileModeUpgradeTitle: "what neon mode adds",
    fileModeUpgradeBody: "Once you run in neon mode, this section becomes real access management instead of a fallback note.",
    fileModeUpgradeBenefitOne: "separate facilitator accounts with owner / operator / observer roles",
    fileModeUpgradeBenefitTwo: "access revocation without rotating a shared password",
    fileModeUpgradeBenefitThree: "session and audit log attribution to a specific person",
    accountTitle: "facilitator account",
    accountEyebrow: "password and session",
    accountDescription: "Manage your own sign-in and review your role in the active workshop instance.",
    passwordCardTitle: "change password",
    currentPasswordLabel: "current password",
    newPasswordLabel: "new password",
    confirmPasswordLabel: "confirm new password",
    revokeSessionsLabel: "sign out other sessions",
    changePasswordButton: "save new password",
    passwordChanged: "Password changed.",
    passwordMismatch: "The new passwords do not match.",
    passwordResetTitle: "password help",
    passwordResetBody: "If you do not remember the password, send yourself a reset link by email.",
    passwordResetButton: "send reset link",
    passwordResetSent: "If the account exists and reset is available, an email has been sent.",
    passwordResetPageTitle: "set a new password",
    passwordResetPageBody: "Open this page from the email link and set a new password for the facilitator account.",
    passwordResetMissingToken: "The reset link does not contain a token. Open the page from the email again.",
    passwordResetButtonConfirm: "set new password",
    passwordResetDone: "Password reset complete. Sign in with the new password.",
    accountFileMode: "Password management is available only in neon mode.",
    resetHelpTitle: "need to change your password?",
    resetHelpBody:
      "Facilitator sign-in runs on Neon Auth. If you know the password, change it after sign-in in the Account section. If you do not know it, you can send a reset link from here.",
  },
} satisfies Record<UiLanguage, Record<string, string>>;
