export type UiLanguage = "cs" | "en";
export const uiLanguageCookieName = "harness_ui_lang";

export function resolveUiLanguage(value: string | undefined): UiLanguage {
  return value === "en" ? "en" : "cs";
}

export function withLang(path: string, lang: UiLanguage) {
  return lang === "cs" ? path : `${path}${path.includes("?") ? "&" : "?"}lang=${lang}`;
}

export const publicCopy = {
  cs: {
    brand: "harness lab",
    navOverview: "přehled",
    navPrinciples: "principy",
    navDetails: "detaily",
    navParticipantAccess: "vstup pro účastníky",
    navRoom: "místnost",
    navTeams: "týmy",
    navNotes: "poznámky",
    navFacilitatorLogin: "vstup pro facilitátora",
    heroEyebrow: "workshop operating system pro týmy, které pracují s ai agenty",
    heroLead: "Celodenní workshop o kontextu, workflow a handoffu pro práci s AI coding agenty.",
    heroBody: "Praktický den s reálným repem: kontext, plán, testy, handoff. Rozhoduje to, co po týmu zůstane.",
    accessEyebrow: "vstup pro účastníky",
    accessTitle: "vstup do kontextu místnosti",
    accessBody:
      "Pokud jste fyzicky v místnosti, facilitátor sdílí event code. Bez něj tato stránka zůstává veřejným přehledem Harness Labu.",
    eventCodeLabel: "event code",
    eventCodePlaceholder: "sdílí facilitátor",
    eventCodeSubmit: "otevřít vrstvu pro účastníky",
    facilitatorLogin: "vstup pro facilitátora",
    publicDetails: "veřejné detaily",
    sampleHint: "Lokální demo běží se sample kódem, proto je pole předvyplněné. V preview a produkci to tak být nemá.",
    principlesEyebrow: "principy",
    principlesTitle: "minimum pravidel, díky kterým může další tým skutečně pokračovat.",
    principleOneTitle: "repo před improvizací",
    principleOneBody: "Důležitý záměr, omezení a další krok patří nejdřív do repa, ne do vzduchu.",
    principleTwoTitle: "ověřujte po malých krocích",
    principleTwoBody: "Každý významný posun co nejdřív uzamkněte důkazem. Menší jistota je lepší než velká improvizace.",
    principleThreeTitle: "pište pro handoff",
    principleThreeBody:
      "Další tým má bez ústního vysvětlování poznat, co funguje, co je křehké a co je bezpečný další krok.",
    detailsWhat: "co to je",
    detailsWhatBody:
      "Harness Lab je praktický workshop o práci s AI agenty v reálném repozitáři. Důraz je na tom, co po týmu zůstane: kontext, pravidla, plán, testy a handoff.",
    detailsParticipants: "pro účastníky",
    detailsParticipantsBody:
      "Účastníci dostanou kontext konkrétní místnosti až po zadání event code. Veřejná stránka zůstává záměrně čistá a neobsahuje živý stav workshop instance.",
    detailsBoundary: "veřejná hranice",
    detailsBoundaryBody:
      "Skutečná data o termínu, místnosti, rosters a facilitaci patří do privátní runtime vrstvy. Public repo a public homepage zůstávají bezpečné a přenositelné.",
    footerBody: "Veřejná vstupní vrstva workshopu o kontextovém inženýrství, práci s repozitářem a handoffu pro ai agenty.",
    footerTop: "nahoru",
    footerParticipantAccess: "vstup pro účastníky",
    participantEyebrow: "vrstva pro účastníky",
    participantTitleFallback: "workshop běží",
    participantBodyRevealed:
      "Continuation shift je odemčený. Čtěte nejdřív repo a handoff předchozího týmu, pak teprve měňte kód.",
    participantBodyHidden:
      "Soustřeďte se na kontext, plán a první reviewable output. Continuation shift se odemkne později.",
    metricCurrentPhase: "aktuální fáze",
    metricNext: "další blok",
    metricSessionUntil: "session do",
    metricReflection: "reflexe",
    sessionEyebrow: "session",
    sessionBody: "Přihlášení platí jen pro data této místnosti. Facilitátor zůstává odděleně na `/admin`.",
    leaveRoomContext: "opustit kontext místnosti",
    roomData: "vaše data z místnosti",
    noRoomData: "Pro tuto session zatím nejsou dostupná žádná data z konkrétní místnosti.",
    sharedRoomNotes: "sdílené poznámky z místnosti",
    invalidCode: "Event code nesedí. Použijte kód sdílený facilitátorem pro tuto místnost.",
    expiredCode: "Tento event code už expiroval. Facilitátor musí vydat nový nebo ho obnovit.",
    unknownCodeError: "Privátní kontext místnosti se nepodařilo odemknout.",
  },
  en: {
    brand: "harness lab",
    navOverview: "overview",
    navPrinciples: "principles",
    navDetails: "details",
    navParticipantAccess: "participant access",
    navRoom: "room",
    navTeams: "teams",
    navNotes: "notes",
    navFacilitatorLogin: "facilitator login",
    heroEyebrow: "workshop operating system for teams using ai agents",
    heroLead: "A full-day workshop on context, workflow, and handoff for teams working with AI coding agents.",
    heroBody: "A practical day built around a real repo: context, plan, tests, handoff. What survives after the team leaves is what matters.",
    accessEyebrow: "participant access",
    accessTitle: "enter room context",
    accessBody:
      "If you are physically in the room, the facilitator shares the event code. Without it, this page stays a public overview of Harness Lab.",
    eventCodeLabel: "event code",
    eventCodePlaceholder: "shared by facilitator",
    eventCodeSubmit: "open participant view",
    facilitatorLogin: "facilitator login",
    publicDetails: "public details",
    sampleHint: "Local demo mode uses a sample code, so the field is prefilled. This should not happen in preview or production.",
    principlesEyebrow: "principles",
    principlesTitle: "the minimum rules that let another team keep going.",
    principleOneTitle: "repo before improvisation",
    principleOneBody: "Intent, constraints, and the next safe step should land in the repo first, not in the air.",
    principleTwoTitle: "verify in small steps",
    principleTwoBody: "Lock meaningful progress with evidence early. Smaller certainty beats larger improvisation.",
    principleThreeTitle: "write for handoff",
    principleThreeBody:
      "The next team should understand what works, what is fragile, and what is safe to do next without an oral briefing.",
    detailsWhat: "what it is",
    detailsWhatBody:
      "Harness Lab is a practical workshop about using AI agents inside a real repository. The focus is what survives after the session: context, rules, plans, tests, and handoff.",
    detailsParticipants: "for participants",
    detailsParticipantsBody:
      "Participants get room-specific context only after the event code. The public page stays intentionally clean and avoids exposing live workshop runtime state.",
    detailsBoundary: "public boundary",
    detailsBoundaryBody:
      "Real dates, rooms, rosters, and facilitation data belong in the private runtime layer. The public repo and homepage stay safe and portable.",
    footerBody: "Public front door for a workshop about context engineering, repository clarity, and handoff for ai agents.",
    footerTop: "top",
    footerParticipantAccess: "participant access",
    participantEyebrow: "participant room",
    participantTitleFallback: "workshop running",
    participantBodyRevealed:
      "The continuation shift is unlocked. Read the previous team's repo and handoff before you change code.",
    participantBodyHidden:
      "Focus on context, the plan, and the first reviewable output. The continuation shift will unlock later.",
    metricCurrentPhase: "current phase",
    metricNext: "next",
    metricSessionUntil: "session until",
    metricReflection: "reflection",
    sessionEyebrow: "session",
    sessionBody: "This sign-in only applies to data for this room. Facilitator access stays separate at `/admin`.",
    leaveRoomContext: "leave room context",
    roomData: "your room data",
    noRoomData: "No room-specific data is available for this session yet.",
    sharedRoomNotes: "shared room notes",
    invalidCode: "The event code does not match. Use the code shared by the facilitator for this room.",
    expiredCode: "This event code has expired. The facilitator must issue a new one or restore it.",
    unknownCodeError: "The private room context could not be unlocked.",
  },
} satisfies Record<UiLanguage, Record<string, string>>;

export const adminCopy = {
  cs: {
    deskEyebrow: "facilitator desk",
    pageTitle: "řízení workshopu",
    pageBody:
      "Chráněný operační panel pro facilitátora. Drží odděleně participant orientaci a live zásahy do workshop instance, aby veřejná plocha zůstala čistá a mobile-first.",
    activeInstance: "aktivní instance",
    currentPhase: "aktuální fáze",
    rotation: "rotace",
    teams: "týmy",
    rotationUnlocked: "odemčeno",
    rotationHidden: "skryto",
    latestArchivePrefix: "Poslední archiv:",
    retentionUntil: "retention do",
    retentionUnset: "nenastaveno",
    workshopStateTitle: "stav workshopu",
    workshopStateEyebrow: "rychlé zásahy do průběhu dne",
    workshopStateDescription: "Použijte na změnu fáze a reset instance. Reset je high-impact operace.",
    moveAgendaTitle: "posunout agendu",
    setCurrentPhase: "nastavit aktuální fázi",
    resetInstanceTitle: "reset workshop instance",
    resetHint: "Přepíše lokální workshop state seedovanou ukázkovou instancí.",
    resetButton: "resetovat data",
    archiveTitle: "archivovat aktuální instanci",
    archivePlaceholder: "volitelné poznámky k archivaci",
    archiveHint: "Uloží snapshot runtime stavu před closeoutem nebo před ručním resetem.",
    archiveButton: "vytvořit archiv",
    continuationTitle: "ovládání continuation shiftu",
    continuationEyebrow: "odemknutí handoff momentu",
    continuationDescription: "Jasně oddělené high-impact ovládání pro reveal nebo hide continuation shiftu.",
    revealTitle: "reveal rotace",
    unlockButton: "odemknout",
    hideAgainButton: "znovu skrýt",
    participantStatePrefix: "Stav na participant ploše:",
    participantStateUnlocked: "předání je odemčeno",
    participantStateHidden: "předání je skryté",
    activeRotationTitle: "aktivní rozpis rotace",
    teamOpsTitle: "operace nad týmy",
    teamOpsEyebrow: "repo a checkpoint management",
    teamOpsDescription: "Formuláře pro registraci týmů a údržbu jejich aktuálního checkpointu.",
    registerTeamTitle: "registrovat nebo upravit tým",
    teamNamePlaceholder: "Tým 5",
    teamCheckpointPlaceholder: "aktuální stav týmu",
    saveTeamButton: "uložit tým",
    editCheckpointTitle: "upravit checkpoint týmu",
    saveCheckpointButton: "uložit checkpoint",
    signalTitle: "sběr signálů",
    signalEyebrow: "intermezzo a progress evidence",
    signalDescription: "Krátké zápisy do feedu a challenge completion, které se pak promítají do workshop rytmu.",
    sprintFeedTitle: "feed sprint checkpointů",
    addUpdateButton: "přidat update",
    completeChallengeTitle: "označit challenge jako splněnou",
    recordCompletionButton: "zapsat completion",
  },
  en: {
    deskEyebrow: "facilitator desk",
    pageTitle: "workshop control",
    pageBody:
      "Protected operations panel for the facilitator. It keeps participant orientation and live workshop actions separate so the public surface stays clean and mobile-first.",
    activeInstance: "active instance",
    currentPhase: "current phase",
    rotation: "rotation",
    teams: "teams",
    rotationUnlocked: "unlocked",
    rotationHidden: "hidden",
    latestArchivePrefix: "Latest archive:",
    retentionUntil: "retention until",
    retentionUnset: "not set",
    workshopStateTitle: "workshop state",
    workshopStateEyebrow: "quick interventions during the day",
    workshopStateDescription: "Use this area to change the phase or reset the instance. Reset is a high-impact operation.",
    moveAgendaTitle: "move agenda",
    setCurrentPhase: "set current phase",
    resetInstanceTitle: "reset workshop instance",
    resetHint: "This overwrites the local workshop state with a seeded sample instance.",
    resetButton: "reset data",
    archiveTitle: "archive current instance",
    archivePlaceholder: "optional archive notes",
    archiveHint: "Stores a runtime snapshot before closeout or before a manual reset.",
    archiveButton: "create archive",
    continuationTitle: "continuation controls",
    continuationEyebrow: "unlock the handoff moment",
    continuationDescription: "A clearly separated high-impact control for revealing or hiding the continuation shift.",
    revealTitle: "rotation reveal",
    unlockButton: "unlock",
    hideAgainButton: "hide again",
    participantStatePrefix: "Participant surface state:",
    participantStateUnlocked: "handoff is unlocked",
    participantStateHidden: "handoff is hidden",
    activeRotationTitle: "active rotation plan",
    teamOpsTitle: "team operations",
    teamOpsEyebrow: "repo and checkpoint management",
    teamOpsDescription: "Forms for registering teams and maintaining their current checkpoint.",
    registerTeamTitle: "register or edit team",
    teamNamePlaceholder: "Team 5",
    teamCheckpointPlaceholder: "current team status",
    saveTeamButton: "save team",
    editCheckpointTitle: "edit team checkpoint",
    saveCheckpointButton: "save checkpoint",
    signalTitle: "signal capture",
    signalEyebrow: "intermezzo and progress evidence",
    signalDescription: "Short feed updates and challenge completion that feed back into the workshop rhythm.",
    sprintFeedTitle: "sprint checkpoint feed",
    addUpdateButton: "add update",
    completeChallengeTitle: "mark challenge as completed",
    recordCompletionButton: "record completion",
  },
} satisfies Record<UiLanguage, Record<string, string>>;
