export type UiLanguage = "cs" | "en";
export const uiLanguageCookieName = "harness_ui_lang";

export function resolveUiLanguage(value: string | undefined): UiLanguage {
  return value === "en" ? "en" : "cs";
}

export function withLang(path: string, lang: UiLanguage) {
  return lang === "cs" ? path : `${path}${path.includes("?") ? "&" : "?"}lang=${lang}`;
}

export const publicCopy = {
  cs: {
    brand: "harness lab",
    navOverview: "přehled",
    navPrinciples: "principy",
    navDetails: "detaily",
    navBlueprint: "blueprint",
    navParticipantAccess: "vstup pro účastníky",
    navRepo: "repo",
    navNext: "další krok",
    navBuild: "práce",
    navReference: "podklady",
    navRoom: "místnost",
    navTeams: "týmy",
    navNotes: "poznámky",
    navFacilitatorLogin: "vstup pro facilitátora",
    heroEyebrow: "workshop pro týmy, které pracují s ai coding agenty",
    heroLead: "Celodenní workshop o tom, jak v týmu pracovat s AI coding agenty tak, aby na výsledek mohl navázat kdokoliv další.",
    heroBody:
      "Nejde o předvádění promptů ani o hackathon energii. Lidé řídí, agenti vykonávají, kontext drží repo, důvěru drží ověření. Úspěch je, když na práci dokáže navázat další tým — bez autorů v místnosti.",
    blueprintLink: "otevřít workshop blueprint",
    blueprintHint:
      "Veřejný blueprint workshopu: jak je postavený den, co patří do repa a co až do živé instance workshopu.",
    accessEyebrow: "vstup pro účastníky",
    accessTitle: "vstup do kontextu místnosti",
    accessBody:
      "Pokud jste v místnosti, facilitátor sdílí kód místnosti. Bez něj tahle stránka zůstává jen veřejným přehledem Harness Labu.",
    eventCodeLabel: "kód místnosti",
    eventCodePlaceholder: "sdílí facilitátor",
    eventCodeSubmit: "otevřít plochu pro účastníky",
    facilitatorLogin: "vstup pro facilitátora",
    publicDetails: "veřejné detaily",
    sampleHint: "V lokálním demu je pole předvyplněné ukázkovým kódem. V preview ani v produkci to tak být nemá.",
    principlesEyebrow: "principy",
    principlesTitle: "tři pravidla, díky kterým je práce s agenty čitelná, ověřitelná a udržitelná.",
    principleOneTitle: "nejdřív mapa, pak pohyb",
    principleOneBody:
      "Než pošlete agenta do dalšího kola, udělejte repo čitelné. Krátké `AGENTS.md`, jasný vstupní bod a viditelný další bezpečný krok znamenají víc než další prompt.",
    principleTwoTitle: "ověřujte dřív, než jdete dál",
    principleTwoBody:
      "Každý důležitý posun co nejdřív opřete o ověření. Menší ověřený krok je cennější než rychlý postup, který se později rozpadne.",
    principleThreeTitle: "pracujte tak, aby se dalo navázat",
    principleThreeBody:
      "Další člověk ani další agent by neměli muset hádat, co se stalo. V repu má být jasné, co platí, co je skutečně ověřené a jaký je další bezpečný krok.",
    structureEyebrow: "struktura dne",
    structureTitle: "pět fází, které den drží pohromadě.",
    structurePhase1Title: "otevření a zarámování",
    structurePhase1Body:
      "Přepnout z hackathon energie na disciplínu pokračování. Úspěch není v tom, kolik kódu vznikne, ale jestli na něj další tým dokáže navázat.",
    structurePhase2Title: "context is king",
    structurePhase2Body:
      "Praktická ukázka, jak lepší kontext mění kvalitu výstupu. Proč AGENTS.md, plán a explicitní hranice předcházejí implementaci.",
    structurePhase3Title: "první build",
    structurePhase3Body:
      "Týmy vstupují do reálného repa. Před obědem: AGENTS.md, plán, první spustitelný check a první ověřený krok.",
    structurePhase4Title: "continuation shift",
    structurePhase4Body:
      "Jiný tým přebírá vaše repo. Nejdřív čte, pak diagnostikuje, teprve pak mění. Co přežije bez autorů v místnosti?",
    structurePhase5Title: "reveal a reflexe",
    structurePhase5Body:
      "Co pomohlo pokračování a co způsobilo tření. Signály z dne se v příštím týdnu promění v praxi.",
    structureOutcome:
      "Workshop neoptimalizuje na počet features. Optimalizuje na kvalitu pokračování.",
    navAgents: "pro agenty",
    agentPopoverTitle: "kontext pro vašeho agenta",
    agentPopoverBody:
      "Zkopírujte prompt a nechte svého AI agenta vysvětlit, co je Harness Lab a jak workshop funguje.",
    agentPopoverCopy: "zkopírovat",
    agentPopoverCopied: "zkopírováno",
    detailsWhat: "co to je",
    detailsWhatBody:
      "Harness Lab je praktický workshop o tom, jak používat AI coding agenty při skutečné týmové práci na softwaru. Důraz je na způsob práce, který zůstává srozumitelný, ověřitelný a použitelný i po dalším předání.",
    detailsParticipants: "pro účastníky",
    detailsParticipantsBody:
      "Účastníci dostanou kontext své místnosti až po zadání kódu místnosti. Veřejná stránka zůstává záměrně obecná a neukazuje živý stav konkrétní instance workshopu.",
    detailsBoundary: "co zůstává neveřejné",
    detailsBoundaryBody:
      "Konkrétní termín, místnost, složení týmů i facilitace patří do privátní instance workshopu. Veřejný dashboard a veřejné repo zůstávají bezpečné a přenositelné.",
    detailsBlueprint: "blueprint workshopu",
    detailsBlueprintBody:
      "Workshopová metoda má v repu vlastní blueprint. Dashboard řídí běžící workshop, ale kanonický popis dne, pravidel a hranic editace zůstává tady.",
    footerBody: "Veřejný přehled workshopu o týmové práci s AI coding agenty.",
    footerTop: "nahoru",
    footerParticipantAccess: "vstup pro účastníky",
    footerBlueprint: "blueprint",
    participantEyebrow: "plocha pro účastníky",
    participantTitleFallback: "workshop běží",
    participantBodyRevealed:
      "Odpolední navázání je otevřené. Nejdřív čtěte README, `AGENTS.md` a plán. Sepište si, co drží, co chybí a jaký je další bezpečný krok. Teprve potom měňte kód.",
    participantBodyHidden:
      "Teď držte pohromadě krátké `AGENTS.md`, plán, build/test postup a první ověřený krok. Odpolední navázání se otevře později.",
    participantGuidanceFallbackLabel: "agenda pro tým",
    participantGuidanceFocusTitle: "co držet teď",
    participantGuidancePreviewBody:
      "Držte pohromadě live moment, další blok a sdílené poznámky z místnosti. Když se zaseknete, vraťte se k mapě repa a nejmenšímu užitečnému ověření.",
    metricCurrentPhase: "aktuální fáze",
    metricNext: "další blok",
    metricSessionUntil: "platí do",
    metricReflection: "reflexe",
    sessionEyebrow: "přístup",
    sessionBody: "Přihlášení platí jen pro data této místnosti. Facilitátor zůstává odděleně na `/admin`.",
    leaveRoomContext: "opustit kontext místnosti",
    roomData: "vaše data z místnosti",
    noRoomData: "Pro tenhle přístup zatím nejsou z konkrétní místnosti dostupná žádná data.",
    teamCheckInsLabel: "check-iny týmu",
    teamCheckInsEmpty: "Zatím žádné check-iny. Napište první, aby si ho tým zapamatoval.",
    teamCheckInFormTitle: "Zapsat check-in",
    teamCheckInContentPlaceholder: "Co se právě děje s vaším týmem? Dvě až tři věty.",
    teamCheckInAuthorPlaceholder: "Kdo píše (volitelné)",
    teamCheckInSubmit: "Zapsat check-in",
    teamCheckInSuccess: "Check-in uložen.",
    teamCheckInMissingContent: "Napište obsah check-inu.",
    teamCheckInMissingPhase: "Zatím není aktivní fáze workshopu.",
    teamCheckInGenericError: "Check-in se nepodařilo uložit.",
    sharedRoomNotes: "sdílené poznámky z místnosti",
    openLinkLabel: "otevřít",
    quoteSourceUnknown: "zdroj neuveden",
    invalidCode: "Kód místnosti nesedí. Použijte kód, který facilitátor sdílí pro tuhle místnost.",
    expiredCode: "Tomuhle kódu místnosti vypršela platnost. Facilitátor musí vydat nový nebo ho obnovit.",
    unknownCodeError: "Privátní kontext místnosti se nepodařilo odemknout.",
  },
  en: {
    brand: "harness lab",
    navOverview: "overview",
    navPrinciples: "principles",
    navDetails: "details",
    navBlueprint: "blueprint",
    navParticipantAccess: "participant access",
    navRepo: "repo",
    navNext: "next",
    navBuild: "build",
    navReference: "reference",
    navRoom: "room",
    navTeams: "teams",
    navNotes: "notes",
    navFacilitatorLogin: "facilitator login",
    heroEyebrow: "workshop for teams working with ai coding agents",
    heroLead: "A full-day workshop on working with AI coding agents so anyone can continue where your team left off.",
    heroBody:
      "Not prompt demos or hackathon energy. Humans steer, agents execute, the repo carries context, verification carries trust. Success is when another team can continue the work without the authors in the room.",
    blueprintLink: "open workshop blueprint",
    blueprintHint:
      "The public workshop blueprint: how the day is structured, what belongs in the repo, and what only exists in the live workshop instance.",
    accessEyebrow: "participant access",
    accessTitle: "enter room context",
    accessBody:
      "If you are physically in the room, the facilitator shares the event code. Without it, this page stays a public overview of Harness Lab.",
    eventCodeLabel: "event code",
    eventCodePlaceholder: "shared by facilitator",
    eventCodeSubmit: "open participant surface",
    facilitatorLogin: "facilitator login",
    publicDetails: "public details",
    sampleHint: "Local demo mode uses a sample code, so the field is prefilled. This should not happen in preview or production.",
    principlesEyebrow: "principles",
    principlesTitle: "three rules that keep work with agents legible, verifiable, and maintainable.",
    principleOneTitle: "map before motion",
    principleOneBody:
      "Before you send the agent on another round, make the repo navigable. A short `AGENTS.md`, a clear entry point, and an obvious next safe step beat one more prompt.",
    principleTwoTitle: "verify before you move on",
    principleTwoBody:
      "Anchor each meaningful step in evidence as early as possible. A smaller verified step is worth more than a faster path that falls apart later.",
    principleThreeTitle: "work so others can continue",
    principleThreeBody:
      "The next person or the next agent should not have to guess what happened. The repo should make clear what holds, what is actually verified, and what the next safe step is.",
    structureEyebrow: "day structure",
    structureTitle: "five phases that hold the day together.",
    structurePhase1Title: "opening and framing",
    structurePhase1Body:
      "Shift from hackathon energy to continuation discipline. Success is not how much code you ship, but whether the next team can pick it up.",
    structurePhase2Title: "context is king",
    structurePhase2Body:
      "A live demonstration of how better context changes output quality. Why AGENTS.md, a plan, and explicit boundaries come before implementation.",
    structurePhase3Title: "build phase",
    structurePhase3Body:
      "Teams enter a real repo. Before lunch: AGENTS.md, a plan, one executable check, and the first verified step.",
    structurePhase4Title: "continuation shift",
    structurePhase4Body:
      "Another team takes over your repo. They read first, diagnose second, change only after they can explain the state. What survives without the authors in the room?",
    structurePhase5Title: "reveal and reflection",
    structurePhase5Body:
      "What helped continuation and what caused friction. Signals from the day become next-week practice.",
    structureOutcome:
      "The workshop does not optimize for feature count. It optimizes for continuation quality.",
    navAgents: "for agents",
    agentPopoverTitle: "context for your agent",
    agentPopoverBody:
      "Copy the prompt and let your AI agent explain what Harness Lab is and how the workshop works.",
    agentPopoverCopy: "copy",
    agentPopoverCopied: "copied",
    detailsWhat: "what it is",
    detailsWhatBody:
      "Harness Lab is a practical workshop about using AI coding agents in real team software work. The focus is on a way of working that stays understandable, verifiable, and usable through handoffs.",
    detailsParticipants: "for participants",
    detailsParticipantsBody:
      "Participants get room-specific context only after the event code. The public page stays intentionally general and does not expose the live state of a specific workshop instance.",
    detailsBoundary: "what stays private",
    detailsBoundaryBody:
      "Real dates, rooms, team assignments, and facilitation data belong in the private workshop instance. The public repo and homepage stay safe and portable.",
    detailsBlueprint: "workshop blueprint",
    detailsBlueprintBody:
      "The workshop method has its own blueprint in the repo. The dashboard operates the live workshop, while the canonical day design, rules, and edit boundaries stay there.",
    footerBody: "Public overview of a workshop about team work with AI coding agents.",
    footerTop: "top",
    footerParticipantAccess: "participant access",
    footerBlueprint: "blueprint",
    participantEyebrow: "participant surface",
    participantTitleFallback: "workshop running",
    participantBodyRevealed:
      "The continuation shift is unlocked. Read README, `AGENTS.md`, and the plan first. Write down what helps, what is missing, and the next safe move before you change code.",
    participantBodyHidden:
      "Focus on a short `AGENTS.md`, the plan, the build/test flow, and the first verified step. The continuation shift will unlock later.",
    participantGuidanceFallbackLabel: "team agenda",
    participantGuidanceFocusTitle: "what to hold now",
    participantGuidancePreviewBody:
      "Keep the live moment, the next block, and shared room notes in view together. If you get stuck, go back to the repo map and the smallest useful verification step.",
    metricCurrentPhase: "current phase",
    metricNext: "next",
    metricSessionUntil: "session until",
    metricReflection: "reflection",
    sessionEyebrow: "session",
    sessionBody: "This sign-in only applies to data for this room. Facilitator access stays separate at `/admin`.",
    leaveRoomContext: "leave room context",
    roomData: "your room data",
    noRoomData: "No room-specific data is available for this session yet.",
    teamCheckInsLabel: "team check-ins",
    teamCheckInsEmpty: "No check-ins yet. Write the first one so the team remembers it.",
    teamCheckInFormTitle: "Record a check-in",
    teamCheckInContentPlaceholder: "What's true about your team right now? Two or three sentences.",
    teamCheckInAuthorPlaceholder: "Who's writing (optional)",
    teamCheckInSubmit: "Record check-in",
    teamCheckInSuccess: "Check-in saved.",
    teamCheckInMissingContent: "Write the check-in content.",
    teamCheckInMissingPhase: "No workshop phase is active yet.",
    teamCheckInGenericError: "Could not save the check-in.",
    sharedRoomNotes: "shared room notes",
    openLinkLabel: "open",
    quoteSourceUnknown: "source not specified",
    invalidCode: "The event code does not match. Use the code shared by the facilitator for this room.",
    expiredCode: "This event code has expired. The facilitator must issue a new one or restore it.",
    unknownCodeError: "The private room context could not be unlocked.",
  },
} satisfies Record<UiLanguage, Record<string, string>>;

export const adminCopy = {
  cs: {
    deskEyebrow: "režie facilitátora",
    pageTitle: "správa workshopů",
    pageBody: "Výběr instancí, vstup do režie a hlavní facilitátorské operace na jednom místě.",
    workspaceEyebrow: "workspace",
    workspaceTitle: "workshopy a jejich instance",
    workspaceBody: "Přehled všech workshopů: co existuje, co je připravené a odkud vstoupit do konkrétní režie.",
    workspaceSummaryTitle: "workspace na první pohled",
    workspaceSearchLabel: "hledat workshop",
    workspaceSearchPlaceholder: "název, id, venue nebo facilitátor",
    workspaceStatusFilterLabel: "stav",
    workspaceSearchButton: "použít filtry",
    workspaceResetFilters: "vyčistit",
    workspaceEmptyTitle: "žádná instance neodpovídá filtru",
    workspaceEmptyBody: "Zkuste jiný dotaz nebo stav. Workspace má ukazovat všechny akce čitelně, ne vás nutit hádat správné id.",
    workspaceOpenInstance: "otevřít řízení",
    workspaceCreateDescription: "Nejdřív založíte akci. Pak se otevře její režie. Zadejte název, datum a místo.",
    workspaceCreateStepsTitle: "co se stane dál",
    workspaceCreateStepOne: "instance se objeví ve workspace přehledu",
    workspaceCreateStepTwo: "otevře se její režie pro živý průběh",
    workspaceCreateStepThree: "plocha pro účastníky zůstává oddělená a navázaná jen na tuto akci",
    workspaceStatsAll: "celkem",
    workspaceStatsCreated: "nové",
    workspaceStatsPrepared: "připravené",
    workspaceStatsRunning: "live",
    workspaceStatsArchived: "archiv",
    workspaceWhenLabel: "termín",
    workspaceWhereLabel: "kde",
    workspaceOwnerLabel: "vlastník",
    workspacePhaseLabel: "fáze",
    workspaceTeamsLabel: "týmy",
    workspaceNextStepLabel: "další krok",
    workspaceNextStepCreated: "Doplňte provozní údaje a otevřete režii.",
    workspaceNextStepPrepared: "Zkontrolujte aktuální fázi, týmy, přístup pro účastníky a jestli checkpointy sbírají evidenci místo dojmů.",
    workspaceNextStepRunning: "Použijte Run pro živý průběh a People pro přeskládání týmů.",
    workspaceNextStepArchived: "Zachovejte historii a případně připravte další běh.",
    workspaceSignalLabel: "plocha pro účastníky",
    workspaceSignalHidden: "plocha pro účastníky skrytá",
    workspaceSignalRevealed: "plocha pro účastníky otevřená",
    controlRoomBack: "zpět na workspace",
    controlRoomBody: "Jedna klidná režie pro tuto instanci. Run drží živý průběh, People drží týmy a Access se Settings zůstávají vedlejší vrstvy.",
    navOverview: "přehled",
    navLive: "live",
    navAgenda: "run",
    navTeams: "týmy",
    navPeople: "lidé",
    navSignals: "signály",
    navAccess: "přístupy",
    navSettings: "nastavení",
    navAccount: "účet",
    activeInstance: "aktivní instance",
    instanceIdLabel: "id instance",
    instanceStatusCreated: "nové",
    instanceStatusPrepared: "připravené",
    instanceStatusRunning: "live",
    instanceStatusArchived: "archivováno",
    instanceStatusRemoved: "odebráno",
    currentPhase: "aktuální fáze",
    rotation: "rotace",
    teams: "týmy",
    liveNow: "právě běží",
    nextUp: "dále",
    signedInAs: "přihlášen jako",
    rotationUnlocked: "odemčeno",
    rotationHidden: "skryto",
    latestArchivePrefix: "Poslední archiv:",
    retentionUntil: "uchovat do",
    retentionUnset: "nenastaveno",
    sectionHint: "Navigace zůstává lehká. Stav je stále vidět nahoře a jednotlivé zásahy mají vlastní bloky.",
    instanceSwitcherTitle: "na čem právě pracujete",
    instanceSwitcherDescription: "Vyberte instanci, se kterou právě pracujete. Všechny zásahy níže míří jen do ní.",
    instanceSelectLabel: "varianta workshopu",
    instanceSelectHint: "Tahle volba zatím mění hlavně participant scénář a nastavení rotace podle velikosti skupiny.",
    instanceBlueprintSummary: "Použije se jediný výchozí blueprint pro střední skupinu, zhruba 15 až 20 lidí.",
    switchInstanceButton: "přepnout instanci",
    createInstanceTitle: "vytvořit novou instanci",
    createInstanceEventTitleLabel: "název akce",
    createInstanceEventTitlePlaceholder: "Harness Lab pro Acme",
    newInstanceIdPlaceholder: "client-hackathon-2026-05",
    instanceDateLabel: "datum",
    instanceVenueLabel: "místo / budova",
    instanceAreaLabel: "lokalita / zóna",
    instanceAddressLabel: "adresa",
    instanceCityPlaceholder: "Studio A",
    instanceDateRangePlaceholder: "12. května 2026",
    instanceVenuePlaceholder: "Místo / budova",
    instanceRoomLabel: "místnost",
    instanceRoomPlaceholder: "Místnost / patro",
    contentLanguageLabel: "jazyk workshopového obsahu",
    contentLanguageCzech: "čeština",
    contentLanguageEnglish: "angličtina",
    instanceAddressPlaceholder: "Adresa nebo orientační bod",
    instanceLocationDetailsPlaceholder: "Další detaily pro facilitátora",
    instanceOwnerPlaceholder: "Ondrej / facilitátorský tým",
    createInstanceButton: "vytvořit instanci",
    removeInstanceTitle: "odebrat aktivní instanci",
    removeInstanceHint: "Odebere ji z aktivního seznamu, ale ponechá archivní historii.",
    removeInstanceButton: "odebrat instanci",
    removeInstanceReviewButton: "zkontrolovat odebrání",
    removeInstanceDialogEyebrow: "potvrzení bezpečnostního zásahu",
    removeInstanceDialogTitle: "opravdu odebrat tuto instanci?",
    removeInstanceDialogDescription:
      "Tohle je druhá vrstva operace. Instance zmizí z aktivního workspace přehledu, ale před odebráním se automaticky vytvoří archiv aktuálního stavu.",
    removeInstanceArchiveNote: "Před odebráním vznikne automatický archiv a historie zůstane zachovaná.",
    removeInstanceConsequenceLabel: "co se stane",
    removeInstanceConsequenceBody: "Instance se přesune mimo aktivní seznam. Otevřená režie už ji nemá brát jako běžící akci.",
    cancelButton: "zrušit",
    confirmRemoveInstanceButton: "potvrdit odebrání",
    overviewTitle: "živý průběh",
    overviewDescription: "Jeden přehled toho, co právě běží, co následuje a co dává smysl udělat teď.",
    workshopStateTitle: "stav workshopu",
    workshopStateEyebrow: "rychlé zásahy do průběhu dne",
    workshopStateDescription: "Tady měníte fázi a v krajním případě resetujete instanci. Reset je zásah s velkým dopadem.",
    moveAgendaTitle: "řízení fáze",
    setCurrentPhase: "posunout live marker",
    agendaSectionTitle: "run",
    agendaSectionDescription: "Run drží živý průběh dne. Vidíte, co běží teď, co přijde dál, spustíte projekci a posunete live marker bez editorského šumu.",
    agendaTimelineTitle: "časová osa dne",
    agendaCurrentTitle: "vybraný moment workshopu",
    phaseControlHint: "Blueprint tady neupravujete. Jen posouváte live marker v této instanci.",
    agendaIndexDescription: "Časová osa zůstává páteří navigace. Otevřete moment, spusťte projekci nebo sem rovnou posuňte live marker.",
    agendaStatusDone: "hotovo",
    agendaStatusCurrent: "právě teď",
    agendaStatusUpcoming: "následuje",
    agendaEditEyebrow: "lokální editace této instance",
    agendaEditTitle: "upravit vybranou položku",
    agendaEditDescription: "Tady upravujete provozní kopii agendy pro tuto instanci. Reset tyto změny zahodí a znovu natáhne blueprint.",
    agendaFieldTitle: "název",
    agendaFieldTime: "čas",
    agendaFieldGoal: "cíl",
    agendaFieldRoomSummary: "shrnutí pro místnost",
    agendaFieldFacilitatorPrompts: "poznámky pro facilitátora",
    agendaFieldWatchFors: "na co si dát pozor",
    agendaFieldCheckpointQuestions: "checkpoint otázky",
    agendaFieldInsertAfter: "vložit za",
    agendaRunnerTitle: "tahák pro facilitátora",
    agendaRunnerDescription: "Krátký tahák pro běžný průchod tímto momentem. Git zůstává kanonický zdroj, tady jen čtete provozní verzi pro živé vedení místnosti.",
    agendaRunnerGoalTitle: "cíl tohoto momentu",
    agendaRunnerSayTitle: "co říct",
    agendaRunnerShowTitle: "co ukázat",
    agendaRunnerDoTitle: "co udělat",
    agendaRunnerWatchTitle: "co hlídat",
    agendaRunnerFallbackTitle: "fallback",
    agendaDetailGoalTitle: "cíl",
    agendaDetailRoomSummaryTitle: "shrnutí pro místnost",
    agendaDetailSourceMaterialTitle: "zdrojové materiály pro facilitátora",
    agendaNewGoalPlaceholder: "Co má tenhle moment udělat",
    agendaNewPromptPlaceholder: "Jedna poznámka nebo otázka na řádek",
    agendaNewWatchForPlaceholder: "Na co si dát pozor",
    agendaNewCheckpointPlaceholder: "Checkpoint otázky",
    saveAgendaItemButton: "uložit položku",
    openEditSheetButton: "upravit tuto položku",
    addAgendaItemTitle: "přidat moment agendy",
    addAgendaItemDescription: "Přidejte agenda moment, který platí jen pro tuto workshop instanci.",
    addAgendaItemButton: "přidat moment",
    openAddAgendaItemButton: "přidat moment agendy",
    openAgendaDetailButton: "detail momentu",
    agendaBackToTimelineButton: "zpět na časovou osu",
    agendaMoveLiveHereButton: "posunout live sem",
    moveUpButton: "posunout výš",
    moveDownButton: "posunout níž",
    removeAgendaItemButton: "odebrat položku",
    agendaSourceTitle: "kde se agenda upravuje",
    agendaSourceBody:
      "Tahle stránka pracuje s provozní kopií agendy pro vybranou instanci. Blueprint zůstává kanonický pro nové importy a reset, ale místní pořadí, názvy, časy i doplněné položky můžete upravit tady bez zásahu do sdíleného blueprintu.",
    agendaRuntimeNotice: "Vybraná položka je provozní objekt této instance. Patří sem projekce, participant zrcadlení i místní úpravy, ne do oddělené live vrstvy.",
    agendaJumpToLiveButton: "skočit na live položku",
    closePanelButton: "zavřít panel",
    runtimeCopyBadge: "provozní kopie",
    customItemBadge: "lokální moment",
    blueprintItemBadge: "moment z blueprintu",
    agendaPresenterGroupTitle: "projekce a scény",
    agendaStorageGroupTitle: "zdroj a ukládání",
    resetInstanceTitle: "resetovat instanci workshopu",
    resetHint: "Znovu natáhne workshop blueprint do této instance a vyčistí místní provozní stav.",
    resetBlueprintSummary: "Reset vrátí instanci na jediný výchozí blueprint pro střední skupinu.",
    resetButton: "resetovat data",
    archiveTitle: "archivovat aktuální instanci",
    archivePlaceholder: "volitelné poznámky k archivaci",
    archiveHint: "Uloží snímek aktuálního stavu před uzavřením nebo před ručním resetem.",
    archiveButton: "vytvořit archiv",
    continuationTitle: "pokračování pro účastníky",
    continuationEyebrow: "odemknutí participant plochy",
    continuationDescription: "Přepínač pro chvíli, kdy se má účastníkům otevřít odpolední plocha pro účastníky.",
    handoffMomentTitle: "plocha pro účastníky",
    handoffMomentLiveDescription: "Rotace právě běží. Tady otevřete participant plochu a držte po ruce i rozpis přesunů.",
    handoffMomentNextDescription: "Další velký přechod je rotace. Participant plochu otevírejte až tady, ne jako trvalý globální přepínač.",
    handoffMomentJumpButton: "detail rotace",
    revealTitle: "stav participant plochy",
    unlockButton: "odemknout",
    hideAgainButton: "znovu skrýt",
    participantStatePrefix: "Stav na participant ploše:",
    participantStateUnlocked: "plocha pro účastníky je otevřená",
    participantStateHidden: "plocha pro účastníky je skrytá",
    rotationSignalTitle: "záznam signálů z rotace",
    rotationSignalDescription: "Zachyťte, co pomohlo nebo zadrhlo, když cizí tým převzal práci. Zápisy zůstávají jen pro facilitátory a u účastníků se neukazují.",
    rotationSignalFreeTextLabel: "co jste viděli",
    rotationSignalFreeTextPlaceholder: "Např. „Tým B našel AGENTS.md za 40 sekund, ale řeší, proč plán odkazuje na neexistující runbook.“",
    rotationSignalTagsLabel: "štítky (oddělené čárkou)",
    rotationSignalTagsPlaceholder: "agents_md_helped, missing_runbook",
    rotationSignalTeamLabel: "přebírající tým (nepovinné)",
    rotationSignalTeamNone: "— bez týmu —",
    rotationSignalSubmit: "uložit signál",
    rotationSignalListTitle: "poslední signály",
    rotationSignalListEmpty: "Zatím žádné signály. Prvním zápisem začnete sbírat learnings pro tento běh.",
    rotationSignalCapturedByLabel: "facilitátor",
    rotationSignalValidationError: "Zápis musí mít text pozorování.",
    participantSurfaceCardTitle: "plocha pro účastníky",
    participantSurfaceCardDescription: "Vedlejší záchranná vrstva pro chvíli, kdy už je rotace pryč, ale potřebujete stav participant plochy ještě upravit.",
    participantSurfaceRecoveryHint: "Na hlavní plochu patří jen samotný přechod. Tady zůstává záloha pro pozdější opravný zásah.",
    presenterCardTitle: "projekce pro místnost",
    presenterCardDescription: "Spusťte projekci pro místnost. Výchozí scéna se řídí aktivní položkou agendy a můžete ji kdykoli přepnout.",
    presenterCurrentSceneLabel: "výchozí scéna",
    presenterOpenCurrentButton: "otevřít projekci",
    presenterOpenParticipantSurfaceButton: "plocha pro účastníky 1:1",
    presenterOpenParticipantButton: "otevřít participant plochu",
    presenterOpenSelectedScene: "otevřít tuto scénu",
    presenterEditSceneButton: "upravit scénu",
    presenterAddSceneButton: "přidat scénu",
    presenterSetDefaultSceneButton: "nastavit jako výchozí",
    presenterShowSceneButton: "zobrazit scénu",
    presenterHideSceneButton: "skrýt scénu",
    presenterRemoveSceneButton: "odebrat scénu",
    presenterMoveSceneUpButton: "posunout scénu výš",
    presenterMoveSceneDownButton: "posunout scénu níž",
    presenterSceneDisabled: "skryto",
    presenterPageEyebrow: "projekce pro místnost",
    presenterBack: "zpět do režie",
    presenterAgendaLabel: "agenda",
    presenterScenesLabel: "scény",
    presenterSourceMaterialTitle: "zdrojový materiál",
    presenterNoSceneTitle: "Pro tuto položku zatím není připravená žádná aktivní scéna.",
    presenterNoSceneBody: "Doplňte obsah pro projekci v dashboardu, přes skill nebo přes API pro facilitátora.",
    presenterParticipantPreviewLabel: "plocha pro účastníky",
    presenterScenePagerLabel: "scéna",
    presenterPreviousSceneButton: "předchozí scéna",
    presenterNextSceneButton: "další scéna",
    presenterRoomPulseLabel: "signál z místnosti",
    openLinkLabel: "otevřít",
    quoteSourceUnknown: "zdroj neuveden",
    openRepoLabel: "otevřít v repu",
    activeRotationTitle: "aktivní rozpis rotace",
    archiveResetTitle: "bezpečnostní zásahy",
    archiveResetDescription: "Archiv a reset patří do druhé vrstvy. Používejte je vědomě, ne místo hlavních zásahů.",
    settingsSafetyEyebrow: "druhá vrstva operací",
    blueprintLinkLabel: "upravit blueprint",
    blueprintLinkHint: "Blueprint upravujte jen tehdy, když chcete změnit výchozí podobu workshopu pro budoucí importy. Jednorázové úpravy této akce patří do provozní instance.",
    presenterRoomBlocksTitle: "bloky pro místnost",
    presenterFacilitatorNotesTitle: "poznámky pro facilitátora",
    sceneEditTitle: "upravit scénu",
    sceneEditDescription: "Tady upravujete provozní kopii projekční scény pro tuto instanci. Běžná cesta vede přes blokový editor a živý náhled, JSON zůstává jen jako kompatibilní payload.",
    sceneAddTitle: "přidat scénu",
    sceneAddDescription: "Přidejte novou scénu k této položce agendy. Scény můžete řadit, skrývat a nastavit jako výchozí.",
    sceneFieldLabel: "název scény",
    sceneFieldType: "typ scény",
    sceneFieldIntent: "záměr",
    sceneFieldChromePreset: "přednastavení chromu",
    sceneFieldTitle: "titulek pro místnost",
    sceneFieldBody: "krátké shrnutí",
    sceneFieldCtaLabel: "text CTA",
    sceneFieldCtaHref: "CTA odkaz",
    sceneFieldFacilitatorNotes: "poznámky pro facilitátora",
    sceneFieldSourceRefs: "zdrojové reference (JSON pole)",
    sceneFieldBlocks: "bloky pro místnost",
    sceneJsonHint: "Editor pod tím stále vytváří stejné JSON pole pro skill a API, ale běžná editace už nemá začínat ručním psaním payloadu.",
    saveSceneButton: "uložit scénu",
    createSceneButton: "vytvořit scénu",
    teamOpsTitle: "operace nad týmy",
    teamOpsEyebrow: "repo a checkpointy",
    teamOpsDescription: "Vyberte tým a upravujte ho v kontextu repo URL, členů a checkpointu. Nový tým založte zvlášť.",
    registerTeamTitle: "registrovat nebo upravit tým",
    editTeamTitle: "upravit vybraný tým",
    editTeamDescription: "Editace je navázaná na zvolený tým, takže nemusíte ručně párovat id a jméno.",
    checkpointFormHint: "Checkpointy zapisujte jako evidenci: co se změnilo, co to ověřuje a jaký je další bezpečný krok.",
    checkpointChangedLabel: "co se změnilo",
    checkpointVerifiedLabel: "co to ověřuje",
    checkpointNextStepLabel: "další bezpečný krok",
    checkpointAtLabel: "čas",
    teamNamePlaceholder: "Tým 5",
    teamCheckpointPlaceholder: "co se změnilo / co to ověřuje / další bezpečný krok",
    createTeamButton: "vytvořit tým",
    updateTeamButton: "uložit změny týmu",
    createAnotherTeamLabel: "nový tým",
    editActionLabel: "upravit",
    saveTeamButton: "uložit tým",
    editCheckpointTitle: "upravit checkpoint týmu",
    saveCheckpointButton: "uložit checkpoint",
    signalTitle: "sběr signálů",
    signalEyebrow: "krátké zápisy a evidence postupu",
    signalDescription: "Krátké živé zápisy a potvrzení splněných challenge. Preferujte evidenci: co se změnilo, co to ověřuje a co má další tým číst jako první.",
    sprintFeedTitle: "přehled sprint checkpointů",
    addUpdateButton: "přidat zápis",
    completeChallengeTitle: "označit challenge jako splněnou",
    recordCompletionButton: "zapsat splnění",
    signInTitle: "přihlášení facilitátora",
    signInBody: "Přístup k operačnímu panelu vyžaduje přihlášení.",
    signInEmailLabel: "e-mail",
    signInPasswordLabel: "heslo",
    signInButton: "přihlásit se",
    signInError: "Neplatné přihlašovací údaje.",
    signOutButton: "odhlásit se",
    signInBackLink: "← zpět na přehled",
    facilitatorsTitle: "správa facilitátorů",
    facilitatorsEyebrow: "přístupy k instanci",
    facilitatorsDescription: "Přidání a odebrání facilitátorů pro tuto instanci workshopu.",
    addFacilitatorTitle: "přidat facilitátora",
    facilitatorEmailPlaceholder: "email@example.com",
    facilitatorRoleLabel: "role",
    addFacilitatorButton: "přidat",
    revokeButton: "odebrat",
    facilitatorListEmpty: "Žádné aktivní přístupy.",
    fileModeFacilitators: "Správa facilitátorů je dostupná jen v neon módu.",
    fileModeFacilitatorsPanelTitle: "lokální přístup ve file módu",
    fileModeFacilitatorsPanelBody:
      "Tahle instance běží bez samostatných účtů. Přístup se sdílí přes lokální Basic Auth a platí pro celou instanci.",
    fileModeAuthModeLabel: "režim přístupu",
    fileModeAuthModeValue: "Basic Auth / sdílený lokální přístup",
    fileModeUsernameLabel: "uživatelské jméno",
    fileModeScopeLabel: "rozsah",
    fileModeScopeValue: "jedna lokální identita pro celou režii",
    fileModeUpgradeTitle: "co získáte v neon módu",
    fileModeUpgradeBody: "Jakmile poběžíte v neon módu, tahle sekce se změní z fallbacku na skutečnou správu přístupů.",
    fileModeUpgradeBenefitOne: "samostatné účty facilitátorů a role owner / operator / observer",
    fileModeUpgradeBenefitTwo: "odebírání přístupu bez sdíleného hesla",
    fileModeUpgradeBenefitThree: "navázání session a audit logu na konkrétní osobu",
    accountTitle: "účet facilitátora",
    accountEyebrow: "heslo a přihlášení",
    accountDescription: "Správa vlastního přihlášení a rychlý přehled role v aktuální instanci.",
    passwordCardTitle: "změnit heslo",
    currentPasswordLabel: "aktuální heslo",
    newPasswordLabel: "nové heslo",
    confirmPasswordLabel: "potvrzení nového hesla",
    revokeSessionsLabel: "odhlásit ostatní přihlášení",
    changePasswordButton: "uložit nové heslo",
    passwordChanged: "Heslo bylo změněno.",
    passwordMismatch: "Nová hesla se neshodují.",
    passwordResetTitle: "pomoc s heslem",
    passwordResetBody: "Pokud si heslo nepamatujete, pošlete si resetovací odkaz na e-mail.",
    passwordResetButton: "poslat reset odkaz",
    passwordResetSent: "Pokud účet existuje a reset je dostupný, e-mail byl odeslán.",
    passwordResetPageTitle: "nastavit nové heslo",
    passwordResetPageBody: "Použijte odkaz z e-mailu a nastavte nové heslo pro facilitátorský účet.",
    passwordResetMissingToken: "Resetovací odkaz neobsahuje token. Otevřete stránku z e-mailu znovu.",
    passwordResetButtonConfirm: "nastavit nové heslo",
    passwordResetDone: "Heslo bylo resetováno. Přihlaste se novým heslem.",
    accountFileMode: "Správa hesla je dostupná jen v neon módu.",
    resetHelpTitle: "potřebujete změnit heslo?",
    resetHelpBody:
      "Přihlášení řeší Neon Auth. Pokud heslo znáte, po přihlášení ho změníte v sekci Účet. Pokud ho neznáte, můžete si poslat resetovací odkaz rovnou odsud.",
    participantAccessEyebrow: "přístup účastníků",
    participantAccessTitle: "sdílený event code",
    participantAccessDescription:
      "Kód pro účastníky patří k této instanci. Vidíte, do kdy platí, jeho identifikátor a podle situace i aktuální kód nebo nově vydanou náhradu.",
    participantAccessStatusLabel: "stav",
    participantAccessStatusActive: "aktivní",
    participantAccessStatusMissing: "nevydaný",
    participantAccessCodeIdLabel: "id kódu",
    participantAccessExpiresLabel: "expiruje",
    participantAccessUnavailableValue: "nedostupné",
    participantAccessCurrentCodeLabel: "aktuální kód",
    participantAccessIssuedCodeLabel: "nově vydaný kód",
    participantAccessIssuedCodeHint:
      "Tohle je jediný okamžik, kdy po rotaci ještě vidíte plný kód. Po uložení zůstává v systému už jen hash.",
    participantAccessRecoverableHint:
      "Tento kód je zatím možné znovu zobrazit díky sample nebo bootstrap konfiguraci. Pokud ho chcete změnit, vydejte nový.",
    participantAccessUnrecoverableHint:
      "Aktuální plný kód už z úložiště zpětně nepřečtete. Pokud ho potřebujete znovu sdílet, vydejte nový kód.",
    participantAccessCustomCodeLabel: "vlastní kód",
    participantAccessCustomCodePlaceholder: "prázdné = vygenerovat nový kód",
    participantAccessIssueHint:
      "Nechte pole prázdné, pokud chcete kód vygenerovat, nebo zadejte vlastní variantu malými písmeny s pomlčkami.",
    participantAccessIssueButton: "vydat nový event code",
  },
  en: {
    deskEyebrow: "facilitator desk",
    pageTitle: "workspace operations",
    pageBody: "Instance selection, control-room entry, and key facilitator operations in one place.",
    workspaceEyebrow: "workspace cockpit",
    workspaceTitle: "workshops and instances",
    workspaceBody: "A clear view of all workshop events: what exists, what is ready, and where to enter focused live control.",
    workspaceSummaryTitle: "workspace at a glance",
    workspaceSearchLabel: "search workshops",
    workspaceSearchPlaceholder: "title, id, venue, or facilitator",
    workspaceStatusFilterLabel: "status",
    workspaceSearchButton: "apply filters",
    workspaceResetFilters: "clear",
    workspaceEmptyTitle: "no instances match the current filters",
    workspaceEmptyBody: "Try a different query or status. The workspace should make events legible, not force you to guess ids.",
    workspaceOpenInstance: "open control room",
    workspaceCreateDescription: "Start with the event record, then enter the control room. Set the event title, date, and place.",
    workspaceCreateStepsTitle: "what happens next",
    workspaceCreateStepOne: "the instance appears in the workspace overview",
    workspaceCreateStepTwo: "its control room opens for live operation",
    workspaceCreateStepThree: "the participant surface stays separate and scoped to this event",
    workspaceStatsAll: "all",
    workspaceStatsCreated: "draft",
    workspaceStatsPrepared: "ready",
    workspaceStatsRunning: "live",
    workspaceStatsArchived: "archive",
    workspaceWhenLabel: "schedule",
    workspaceWhereLabel: "where",
    workspaceOwnerLabel: "owner",
    workspacePhaseLabel: "phase",
    workspaceTeamsLabel: "teams",
    workspaceNextStepLabel: "next step",
    workspaceNextStepCreated: "Add runtime details and enter the control room.",
    workspaceNextStepPrepared: "Check the live phase, teams, participant access, and whether checkpoints ask for evidence instead of vibes.",
    workspaceNextStepRunning: "Use Run for live operation and People for team reshaping.",
    workspaceNextStepArchived: "Keep the history intact and prepare the next run if needed.",
    workspaceSignalLabel: "participant surface",
    workspaceSignalHidden: "participant surface hidden",
    workspaceSignalRevealed: "participant surface open",
    controlRoomBack: "back to workspace",
    controlRoomBody: "One calm control room for this instance. Run holds the live moment, People holds team shaping, and Access/Settings stay secondary.",
    navOverview: "overview",
    navLive: "live",
    navAgenda: "run",
    navTeams: "teams",
    navPeople: "people",
    navSignals: "signals",
    navAccess: "access",
    navSettings: "settings",
    navAccount: "account",
    activeInstance: "active instance",
    instanceIdLabel: "instance id",
    instanceStatusCreated: "draft",
    instanceStatusPrepared: "ready",
    instanceStatusRunning: "live",
    instanceStatusArchived: "archived",
    instanceStatusRemoved: "removed",
    currentPhase: "current phase",
    rotation: "rotation",
    teams: "teams",
    liveNow: "live now",
    nextUp: "next up",
    signedInAs: "signed in as",
    rotationUnlocked: "unlocked",
    rotationHidden: "hidden",
    latestArchivePrefix: "Latest archive:",
    retentionUntil: "retention until",
    retentionUnset: "not set",
    sectionHint: "Navigation stays light. Status stays visible at the top, and actions live in their own sections.",
    instanceSwitcherTitle: "control scope",
    instanceSwitcherDescription: "Choose the instance you are operating. Every action below applies only to that instance.",
    instanceSelectLabel: "workshop variant",
    instanceSelectHint: "This currently changes the participant scenario and rotation setup based on group size.",
    instanceBlueprintSummary: "This uses the single default blueprint for a medium-sized group, about 15 to 20 people.",
    switchInstanceButton: "switch instance",
    createInstanceTitle: "create a new instance",
    createInstanceEventTitleLabel: "event title",
    createInstanceEventTitlePlaceholder: "Harness Lab for Acme",
    newInstanceIdPlaceholder: "client-hackathon-2026-05",
    instanceDateLabel: "date",
    instanceVenueLabel: "venue / building",
    instanceAreaLabel: "area / zone",
    instanceAddressLabel: "address",
    instanceCityPlaceholder: "Studio A",
    instanceDateRangePlaceholder: "May 12, 2026",
    instanceVenuePlaceholder: "venue / building",
    instanceRoomLabel: "room",
    instanceRoomPlaceholder: "room / floor",
    contentLanguageLabel: "workshop content language",
    contentLanguageCzech: "Czech",
    contentLanguageEnglish: "English",
    instanceAddressPlaceholder: "address or landmark",
    instanceLocationDetailsPlaceholder: "additional facilitator-only context",
    instanceOwnerPlaceholder: "Ondrej / facilitator crew",
    createInstanceButton: "create instance",
    removeInstanceTitle: "remove active instance",
    removeInstanceHint: "Removes it from the active list while keeping archive history intact.",
    removeInstanceButton: "remove instance",
    removeInstanceReviewButton: "review removal",
    removeInstanceDialogEyebrow: "confirm safety action",
    removeInstanceDialogTitle: "remove this instance?",
    removeInstanceDialogDescription:
      "This is a second-layer action. The instance leaves the active workspace list, and an automatic archive of the runtime state is created before removal.",
    removeInstanceArchiveNote: "A pre-remove archive is created automatically and the history stays intact.",
    removeInstanceConsequenceLabel: "what happens next",
    removeInstanceConsequenceBody:
      "The instance moves out of the active list. Open control-room sessions should no longer treat it as a live event.",
    cancelButton: "cancel",
    confirmRemoveInstanceButton: "confirm removal",
    overviewTitle: "live control",
    overviewDescription: "One view of what is live, what comes next, and which facilitator actions matter right now.",
    workshopStateTitle: "workshop state",
    workshopStateEyebrow: "quick interventions during the day",
    workshopStateDescription: "Use this area to change the phase or reset the instance. Reset is a high-impact operation.",
    moveAgendaTitle: "phase control",
    setCurrentPhase: "move live marker",
    agendaSectionTitle: "run",
    agendaSectionDescription: "Run is the agenda-centered live runner. Show what is live now, what comes next, launch projection, and move the live marker without editor chrome.",
    agendaTimelineTitle: "day timeline",
    agendaCurrentTitle: "selected workshop moment",
    phaseControlHint: "This does not edit the blueprint. It only moves the live agenda marker inside the runtime instance.",
    agendaIndexDescription: "Use the timeline for both navigation and fast intervention. Open the moment, launch the room view, or move the live marker directly from here.",
    agendaStatusDone: "done",
    agendaStatusCurrent: "live now",
    agendaStatusUpcoming: "up next",
    agendaEditEyebrow: "local editing for this instance",
    agendaEditTitle: "edit selected item",
    agendaEditDescription: "This edits the runtime copy of the agenda for this instance. Reset discards these changes and re-imports from the blueprint.",
    agendaFieldTitle: "title",
    agendaFieldTime: "time",
    agendaFieldGoal: "goal",
    agendaFieldRoomSummary: "room summary",
    agendaFieldFacilitatorPrompts: "facilitator prompts",
    agendaFieldWatchFors: "watch fors",
    agendaFieldCheckpointQuestions: "checkpoint questions",
    agendaFieldInsertAfter: "insert after",
    agendaRunnerTitle: "facilitator runner",
    agendaRunnerDescription: "A short run sheet for the normal path of this moment. Git stays canonical; this surface only reads the agenda-owned live-facilitation view.",
    agendaRunnerGoalTitle: "runner goal",
    agendaRunnerSayTitle: "say",
    agendaRunnerShowTitle: "show",
    agendaRunnerDoTitle: "do",
    agendaRunnerWatchTitle: "watch",
    agendaRunnerFallbackTitle: "fallback",
    agendaDetailGoalTitle: "goal",
    agendaDetailRoomSummaryTitle: "room summary",
    agendaDetailSourceMaterialTitle: "facilitator source material",
    agendaNewGoalPlaceholder: "What this moment needs to achieve",
    agendaNewPromptPlaceholder: "One prompt or question per line",
    agendaNewWatchForPlaceholder: "What to watch for",
    agendaNewCheckpointPlaceholder: "Checkpoint questions",
    saveAgendaItemButton: "save item",
    openEditSheetButton: "edit this item",
    addAgendaItemTitle: "add agenda moment",
    addAgendaItemDescription: "Add an agenda moment that exists only for this workshop instance.",
    addAgendaItemButton: "add moment",
    openAddAgendaItemButton: "add agenda moment",
    openAgendaDetailButton: "moment detail",
    agendaBackToTimelineButton: "back to timeline",
    agendaMoveLiveHereButton: "move live here",
    moveUpButton: "move up",
    moveDownButton: "move down",
    removeAgendaItemButton: "remove item",
    agendaSourceTitle: "where the agenda is edited",
    agendaSourceBody:
      "This page works on the runtime agenda copy for the selected instance. The blueprint remains canonical for future imports and resets, but local order, labels, times, and added items can be changed here without mutating the shared blueprint.",
    agendaRuntimeNotice: "The selected item is the runtime operating object. Projection, participant 1:1, and local editing belong here instead of a separate live product.",
    agendaJumpToLiveButton: "jump to live item",
    closePanelButton: "close panel",
    runtimeCopyBadge: "runtime copy",
    customItemBadge: "instance-only moment",
    blueprintItemBadge: "blueprint moment",
    agendaPresenterGroupTitle: "room screen and scenes",
    agendaStorageGroupTitle: "source and storage",
    resetInstanceTitle: "reset workshop instance",
    resetHint: "This re-imports the workshop blueprint into this instance and clears local runtime state.",
    resetBlueprintSummary: "Reset restores the single default blueprint for a medium-sized group.",
    resetButton: "reset data",
    archiveTitle: "archive current instance",
    archivePlaceholder: "optional archive notes",
    archiveHint: "Stores a runtime snapshot before closeout or before a manual reset.",
    archiveButton: "create archive",
    continuationTitle: "participant continuation",
    continuationEyebrow: "unlock the participant surface",
    continuationDescription: "The switch for the moment when participants should see the afternoon participant surface.",
    handoffMomentTitle: "participant surface",
    handoffMomentLiveDescription: "Rotation is live now. Open the participant surface here and keep the rotation map close at hand.",
    handoffMomentNextDescription: "Rotation is the next major transition. Open the participant surface here when the room reaches it, not as a permanent global toggle.",
    handoffMomentJumpButton: "rotation detail",
    revealTitle: "participant surface state",
    unlockButton: "unlock",
    hideAgainButton: "hide again",
    participantStatePrefix: "Participant surface state:",
    participantStateUnlocked: "participant surface is open",
    participantStateHidden: "participant surface is hidden",
    rotationSignalTitle: "rotation signals",
    rotationSignalDescription: "Capture what helped or what caught the receiving team. Entries stay facilitator-private and never surface to participants.",
    rotationSignalFreeTextLabel: "what you observed",
    rotationSignalFreeTextPlaceholder: "e.g. \"Team B found AGENTS.md in 40 seconds but is stuck because the plan references   runbook that does not exist.\"",
    rotationSignalTagsLabel: "tags (comma separated)",
    rotationSignalTagsPlaceholder: "agents_md_helped, missing_runbook",
    rotationSignalTeamLabel: "receiving team (optional)",
    rotationSignalTeamNone: "— no team —",
    rotationSignalSubmit: "save signal",
    rotationSignalListTitle: "recent signals",
    rotationSignalListEmpty: "No signals captured yet. Your first entry starts the learnings log for this cohort.",
    rotationSignalCapturedByLabel: "facilitator",
    rotationSignalValidationError: "Entry must have observation text.",
    participantSurfaceCardTitle: "participant surface",
    participantSurfaceCardDescription: "A secondary recovery layer for the moment when rotation is already past, but you still need to correct the participant state.",
    participantSurfaceRecoveryHint: "The live canvas should only promote the transition itself. This stays as the fallback recovery control.",
    presenterCardTitle: "room screen",
    presenterCardDescription: "Launch the presenter-safe room output. The default scene follows the active agenda item and can be switched at any time.",
    presenterCurrentSceneLabel: "default scene",
    presenterOpenCurrentButton: "open room screen",
    presenterOpenParticipantSurfaceButton: "participant surface 1:1",
    presenterOpenParticipantButton: "participant walkthrough",
    presenterOpenSelectedScene: "open this scene",
    presenterEditSceneButton: "edit scene",
    presenterAddSceneButton: "add scene",
    presenterSetDefaultSceneButton: "set as default",
    presenterShowSceneButton: "show scene",
    presenterHideSceneButton: "hide scene",
    presenterRemoveSceneButton: "remove scene",
    presenterMoveSceneUpButton: "move scene up",
    presenterMoveSceneDownButton: "move scene down",
    presenterSceneDisabled: "hidden",
    presenterPageEyebrow: "room screen",
    presenterBack: "back to control room",
    presenterAgendaLabel: "agenda",
    presenterScenesLabel: "scenes",
    presenterSourceMaterialTitle: "source material",
    presenterNoSceneTitle: "There is no active scene configured for this agenda item yet.",
    presenterNoSceneBody: "Add room-facing content in the dashboard, through the skill, or through the facilitator API.",
    presenterParticipantPreviewLabel: "participant surface",
    presenterScenePagerLabel: "scene",
    presenterPreviousSceneButton: "previous scene",
    presenterNextSceneButton: "next scene",
    presenterRoomPulseLabel: "room pulse",
    openLinkLabel: "open",
    quoteSourceUnknown: "source not specified",
    openRepoLabel: "open in repo",
    activeRotationTitle: "active rotation plan",
    archiveResetTitle: "safety actions",
    archiveResetDescription: "Archive and reset belong on a second layer. They should never compete with the primary controls.",
    settingsSafetyEyebrow: "second-layer operations",
    blueprintLinkLabel: "edit blueprint",
    blueprintLinkHint: "Edit the blueprint only when you want to change the workshop default for future imports. One-off event changes belong in the runtime instance.",
    presenterRoomBlocksTitle: "room blocks",
    presenterFacilitatorNotesTitle: "facilitator notes",
    sceneEditTitle: "edit scene",
    sceneEditDescription: "This edits the runtime copy of the room scene for this instance. The normal path is the block editor plus live preview; JSON remains only as the compatibility payload.",
    sceneAddTitle: "add scene",
    sceneAddDescription: "Add a new scene to this agenda item. Scenes can be reordered, hidden, and set as default.",
    sceneFieldLabel: "scene label",
    sceneFieldType: "scene type",
    sceneFieldIntent: "intent",
    sceneFieldChromePreset: "chrome preset",
    sceneFieldTitle: "room title",
    sceneFieldBody: "short summary",
    sceneFieldCtaLabel: "CTA label",
    sceneFieldCtaHref: "CTA link",
    sceneFieldFacilitatorNotes: "facilitator notes",
    sceneFieldSourceRefs: "source refs (JSON array)",
    sceneFieldBlocks: "room blocks",
    sceneJsonHint: "The editor still produces the same JSON array for the skill and API path, but routine authoring should no longer start with hand-written payloads.",
    saveSceneButton: "save scene",
    createSceneButton: "create scene",
    teamOpsTitle: "team operations",
    teamOpsEyebrow: "repo and checkpoint management",
    teamOpsDescription: "Operate around real teams. Select a team to edit repo URL, members, and checkpoint in context, and create new teams separately.",
    registerTeamTitle: "register or edit team",
    editTeamTitle: "edit selected team",
    editTeamDescription: "Editing stays attached to the selected team so you do not have to manually match ids and names.",
    checkpointFormHint: "Capture checkpoints as evidence: what changed, what verifies it, and the next safe move.",
    checkpointChangedLabel: "what changed",
    checkpointVerifiedLabel: "what verifies it",
    checkpointNextStepLabel: "next safe move",
    checkpointAtLabel: "time",
    teamNamePlaceholder: "Team 5",
    teamCheckpointPlaceholder: "what changed / what verifies it / next safe move",
    createTeamButton: "create team",
    updateTeamButton: "save team changes",
    createAnotherTeamLabel: "new team",
    editActionLabel: "edit",
    saveTeamButton: "save team",
    editCheckpointTitle: "edit team checkpoint",
    saveCheckpointButton: "save checkpoint",
    signalTitle: "signal capture",
    signalEyebrow: "intermezzo and progress evidence",
    signalDescription: "Short live updates and challenge completion. Prefer evidence: what changed, what verifies it, and what the next team should read first.",
    sprintFeedTitle: "sprint checkpoint feed",
    addUpdateButton: "add update",
    completeChallengeTitle: "mark challenge as completed",
    recordCompletionButton: "record completion",
    signInTitle: "facilitator sign-in",
    signInBody: "Access to the operations panel requires authentication.",
    signInEmailLabel: "email",
    signInPasswordLabel: "password",
    signInButton: "sign in",
    signInError: "Invalid credentials.",
    signOutButton: "sign out",
    signInBackLink: "← back to overview",
    facilitatorsTitle: "facilitator management",
    facilitatorsEyebrow: "instance access",
    facilitatorsDescription: "Add and remove facilitators for this workshop instance.",
    addFacilitatorTitle: "add facilitator",
    facilitatorEmailPlaceholder: "email@example.com",
    facilitatorRoleLabel: "role",
    addFacilitatorButton: "add",
    revokeButton: "revoke",
    facilitatorListEmpty: "No active grants.",
    fileModeFacilitators: "Facilitator management requires neon mode.",
    fileModeFacilitatorsPanelTitle: "local access in file mode",
    fileModeFacilitatorsPanelBody:
      "This instance is running without per-user grants. Access is shared through local Basic Auth and the scope stays at the whole-instance level.",
    fileModeAuthModeLabel: "access mode",
    fileModeAuthModeValue: "Basic Auth / shared local access",
    fileModeUsernameLabel: "username",
    fileModeScopeLabel: "scope",
    fileModeScopeValue: "one local identity for the whole facilitator desk",
    fileModeUpgradeTitle: "what neon mode adds",
    fileModeUpgradeBody: "Once you run in neon mode, this section becomes real access management instead of a fallback note.",
    fileModeUpgradeBenefitOne: "separate facilitator accounts with owner / operator / observer roles",
    fileModeUpgradeBenefitTwo: "access revocation without rotating a shared password",
    fileModeUpgradeBenefitThree: "session and audit log attribution to a specific person",
    accountTitle: "facilitator account",
    accountEyebrow: "password and session",
    accountDescription: "Manage your own sign-in and review your role in the active workshop instance.",
    passwordCardTitle: "change password",
    currentPasswordLabel: "current password",
    newPasswordLabel: "new password",
    confirmPasswordLabel: "confirm new password",
    revokeSessionsLabel: "sign out other sessions",
    changePasswordButton: "save new password",
    passwordChanged: "Password changed.",
    passwordMismatch: "The new passwords do not match.",
    passwordResetTitle: "password help",
    passwordResetBody: "If you do not remember the password, send yourself a reset link by email.",
    passwordResetButton: "send reset link",
    passwordResetSent: "If the account exists and reset is available, an email has been sent.",
    passwordResetPageTitle: "set a new password",
    passwordResetPageBody: "Open this page from the email link and set a new password for the facilitator account.",
    passwordResetMissingToken: "The reset link does not contain a token. Open the page from the email again.",
    passwordResetButtonConfirm: "set new password",
    passwordResetDone: "Password reset complete. Sign in with the new password.",
    accountFileMode: "Password management is available only in neon mode.",
    resetHelpTitle: "need to change your password?",
    resetHelpBody:
      "Facilitator sign-in runs on Neon Auth. If you know the password, change it after sign-in in the Account section. If you do not know it, you can send a reset link from here.",
    participantAccessEyebrow: "participant access",
    participantAccessTitle: "shared event code",
    participantAccessDescription:
      "The participant code belongs to this workshop instance. You can inspect its expiry and code id, and either see the current raw code when it is still recoverable or issue a fresh replacement.",
    participantAccessStatusLabel: "status",
    participantAccessStatusActive: "active",
    participantAccessStatusMissing: "not issued",
    participantAccessCodeIdLabel: "code id",
    participantAccessExpiresLabel: "expires",
    participantAccessUnavailableValue: "unavailable",
    participantAccessCurrentCodeLabel: "current code",
    participantAccessIssuedCodeLabel: "newly issued code",
    participantAccessIssuedCodeHint:
      "This is the only guaranteed moment when you can still see the raw code after a rotation. After saving, the runtime keeps only the hash.",
    participantAccessRecoverableHint:
      "This code is still recoverable from sample or bootstrap configuration. Issue a new one if you want to replace it.",
    participantAccessUnrecoverableHint:
      "The current raw code can no longer be read back from the hash-only store. If you need to share it again, issue a new code.",
    participantAccessCustomCodeLabel: "custom code",
    participantAccessCustomCodePlaceholder: "leave blank to generate a new code",
    participantAccessIssueHint:
      "Leave the field blank for a generated code, or enter your own lowercase hyphenated code.",
    participantAccessIssueButton: "issue new event code",
  },
} satisfies Record<UiLanguage, Record<string, string>>;
