ALTER TABLE workshop_instances
  ADD COLUMN IF NOT EXISTS blueprint_id TEXT NOT NULL DEFAULT 'harness-lab-core-day',
  ADD COLUMN IF NOT EXISTS blueprint_version INTEGER NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS imported_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS removed_at TIMESTAMPTZ;
